import type { Activity } from "./types";

// Generated by scripts/collection/import-live-activities.mjs at 2026-05-12T08:07:06.168Z.
// Source report: /Users/yangyingjia/Shenzhen Learning Hub/docs/superpowers/reports/live-source-calibration-2026-05-12.json
export const liveCollectedActivities = [
  {
    "id": "live-shenzhen-conference-platform-1a479b24fe",
    "slug": "国际数字能源展-1a479b24fe",
    "title": "国际数字能源展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-13T02:00:00.000Z",
    "endAt": "2026-05-13T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.ideesz.com/",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-conference-platform-df516a522b",
    "slug": "深圳智慧养老展-df516a522b",
    "title": "深圳智慧养老展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-14T02:00:00.000Z",
    "endAt": "2026-05-14T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szwbzl.com/zdxm",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-conference-platform-7c5e5ecb17",
    "slug": "26-27赛季hyrox健身跑深圳站-7c5e5ecb17",
    "title": "26|27赛季HYROX健身跑深圳站",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-15T02:00:00.000Z",
    "endAt": "2026-05-15T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://hyrox.com/",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-conference-platform-dafc8843f4",
    "slug": "2026第三届深圳国际耳机展-dafc8843f4",
    "title": "2026第三届深圳国际耳机展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-16T02:00:00.000Z",
    "endAt": "2026-05-16T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.audioexpo.net/?news_12/=",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-conference-platform-6e11304279",
    "slug": "2026全球医疗健康展览会暨第四届深圳生殖医学健康大会-6e11304279",
    "title": "2026全球医疗健康展览会暨第四届深圳生殖医学健康大会",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-17T02:00:00.000Z",
    "endAt": "2026-05-17T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.nexpoworld.com/",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-eventbrite-shenzhen-ce0c516c94",
    "slug": "happy-french-wednesday-free-social-night-at-happy-valley-ce0c516c94",
    "title": "Happy French Wednesday: Free Social Night at Happy Valley",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Eventbrite 深圳"
    ],
    "district": "福田",
    "venue": "Eventbrite 深圳",
    "address": "Eventbrite 深圳",
    "startAt": "2026-05-13T00:00:00.000Z",
    "endAt": "2026-05-13T02:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.eventbrite.hk/e/happy-french-wednesday-free-social-night-at-happy-valley-tickets-1988055642945",
    "sourceId": "eventbrite-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-eventbrite-shenzhen-962476d1ee",
    "slug": "affordable-art-fair-hong-kong-2026-14-17-may-962476d1ee",
    "title": "Affordable Art Fair Hong Kong 2026 | 14-17 May",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Eventbrite 深圳",
      "展会"
    ],
    "district": "福田",
    "venue": "Eventbrite 深圳",
    "address": "Eventbrite 深圳",
    "startAt": "2026-05-14T00:00:00.000Z",
    "endAt": "2026-05-14T02:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.eventbrite.com/e/affordable-art-fair-hong-kong-2026-14-17-may-registration-1740893010859",
    "sourceId": "eventbrite-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-eventbrite-shenzhen-f0e2042163",
    "slug": "mit-hkma-aof-hkimr-joint-seminar-f0e2042163",
    "title": "MIT-HKMA-AoF/HKIMR Joint Seminar",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Eventbrite 深圳"
    ],
    "district": "福田",
    "venue": "Eventbrite 深圳",
    "address": "Eventbrite 深圳",
    "startAt": "2026-05-15T00:00:00.000Z",
    "endAt": "2026-05-15T02:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.eventbrite.com/e/mit-hkma-aofhkimr-joint-seminar-by-professor-robert-townsend-tickets-1987370092445",
    "sourceId": "eventbrite-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-eventbrite-shenzhen-1fe99b82bb",
    "slug": "hong-kong-the-rise-of-machine-customers-other-hkg-1fe99b82bb",
    "title": "Hong Kong - The Rise of Machine Customers_Other_HKG",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Eventbrite 深圳"
    ],
    "district": "福田",
    "venue": "Eventbrite 深圳",
    "address": "Eventbrite 深圳",
    "startAt": "2026-05-17T00:00:00.000Z",
    "endAt": "2026-05-17T02:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.eventbrite.sg/e/hong-kong-the-rise-of-machine-customers-other-hkg-tickets-1988276112375",
    "sourceId": "eventbrite-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-eventbrite-shenzhen-d4445399a5",
    "slug": "aia-vitality-hub-mindfulness-meditation-正念與冥想-d4445399a5",
    "title": "AIA Vitality Hub | Mindfulness & Meditation 正念與冥想",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Eventbrite 深圳"
    ],
    "district": "福田",
    "venue": "Eventbrite 深圳",
    "address": "Eventbrite 深圳",
    "startAt": "2026-05-21T00:00:00.000Z",
    "endAt": "2026-05-21T02:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.eventbrite.hk/e/aia-vitality-hub-mindfulness-meditation-tickets-1988064273760",
    "sourceId": "eventbrite-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-743f56d91b",
    "slug": "枫丹乐影-张鼎萨克斯独奏音乐会-743f56d91b",
    "title": "《枫丹乐影》张鼎萨克斯独奏音乐会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-05-23T02:00:00.000Z",
    "endAt": "2026-05-23T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.douban.com/event/37826917/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-7f95309c60",
    "slug": "西班牙钢琴王子马里奥2026巡演-深圳站-7f95309c60",
    "title": "西班牙钢琴王子马里奥2026巡演-深圳站",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-05-24T02:00:00.000Z",
    "endAt": "2026-05-24T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.douban.com/event/37743155/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-09bc5e4d88",
    "slug": "暑期带娃必体验-探索川剧变脸的奇妙世界-09bc5e4d88",
    "title": "暑期带娃必体验|探索川剧变脸的奇妙世界",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-05-13T02:00:00.000Z",
    "endAt": "2026-05-13T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.douban.com/event/37309570/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-317646a754",
    "slug": "to-mozart-纪念莫扎特诞辰270周年暨中奥建交55周年-钢琴四手联弹专场音乐会-317646a754",
    "title": "To Mozart! 纪念莫扎特诞辰270周年暨中奥建交55周年 钢琴四手联弹专场音乐会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-05-14T02:00:00.000Z",
    "endAt": "2026-05-14T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.douban.com/event/37840780/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-ead71238db",
    "slug": "源起华夏-月球冒险之旅-大型vr沉浸探索-ead71238db",
    "title": "《源起华夏 月球冒险之旅》大型VR沉浸探索",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-05-15T02:00:00.000Z",
    "endAt": "2026-05-15T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.douban.com/event/37309455/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-8addf2b43a",
    "slug": "数据驱动业务增长-ai-加速原力觉醒-e3-pro-企业智能中台-鞋服版全国巡讲-杭州站-8addf2b43a",
    "title": "数据驱动业务增长 AI 加速原力觉醒——E3 + PRO 企业智能中台-鞋服版全国巡讲 · 杭州站",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动",
      "AI"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-05-16T02:00:00.000Z",
    "endAt": "2026-05-16T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/shu-ju-qu-dong-ye-wu-zeng-zhang-ai-jia-su-yuan-li-jue-xing-e",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-694733b477",
    "slug": "首届-ai-仿真人短剧大会-新视界-新规则-694733b477",
    "title": "首届 AI 仿真人短剧大会 | 新视界 新规则",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动",
      "AI"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-05-17T02:00:00.000Z",
    "endAt": "2026-05-17T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/shou-jie-ai-fang-zhen-ren-duan-ju-da-hui-xin-shi-jie-xin-gui",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-36b57de895",
    "slug": "具身智能生态大会-36b57de895",
    "title": "具身智能生态大会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-05-18T02:00:00.000Z",
    "endAt": "2026-05-18T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/ju-shen-zhi-neng-sheng-tai-da-hui",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-e1c0049a78",
    "slug": "ai-落地实战-openclaw-与-agent-在企业中的真实应用案例-e1c0049a78",
    "title": "AI 落地实战：OpenClaw 与 Agent 在企业中的真实应用案例",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动",
      "AI"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-05-19T02:00:00.000Z",
    "endAt": "2026-05-19T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/ai-luo-di-shi-zhan-openclaw-yu-agent-zai-qi-ye-zhong-de-zhen",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-62737edee8",
    "slug": "aing-eco-ai硬件出海专场-62737edee8",
    "title": "AING ECO | AI硬件出海专场",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动",
      "AI"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-05-20T02:00:00.000Z",
    "endAt": "2026-05-20T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/aing-eco-ai-ying-jian-chu-hai-zhuan-chang",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-huodongxing-shenzhen-4263269855",
    "slug": "ai赋能跨境-国货热卖全球-2026第二届跨境电商生态链展览会-4263269855",
    "title": "「AI赋能跨境 国货热卖全球」2026第二届跨境电商生态链展览会",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "活动行深圳",
      "AI",
      "展会"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-05-21T02:00:00.000Z",
    "endAt": "2026-05-21T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.huodongxing.com/event/7849662707300",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-huodongxing-shenzhen-dd74dd9770",
    "slug": "倒计时2天-2026-ccee雨果跨境选品大会-dd74dd9770",
    "title": "【倒计时2天】2026 CCEE雨果跨境选品大会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "活动行深圳"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-05-22T02:00:00.000Z",
    "endAt": "2026-05-22T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.huodongxing.com/event/8844211344400",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-huodongxing-shenzhen-29c0872026",
    "slug": "agic2026深圳人工智能展-29c0872026",
    "title": "AGIC2026深圳人工智能展",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "活动行深圳",
      "AI",
      "展会"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-05-23T02:00:00.000Z",
    "endAt": "2026-05-23T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.huodongxing.com/event/5859922218300",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-huodongxing-shenzhen-dae2d56b68",
    "slug": "孩子分数不理想-这条-全日制本科-捷径千万别错过-dae2d56b68",
    "title": "孩子分数不理想？这条「全日制本科」捷径千万别错过！",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "活动行深圳"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-05-24T02:00:00.000Z",
    "endAt": "2026-05-24T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.huodongxing.com/event/3860344214800",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": false
  },
  {
    "id": "live-huodongxing-shenzhen-818a547a6d",
    "slug": "gaic全球人工智能大会-818a547a6d",
    "title": "GAIC全球人工智能大会",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "活动行深圳",
      "AI"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-05-13T02:00:00.000Z",
    "endAt": "2026-05-13T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.huodongxing.com/event/1858948610000",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-60ae744b46",
    "slug": "whatsapp-group-for-event-updates-認識國際朋友-60ae744b46",
    "title": "WhatsApp group for event updates 認識國際朋友",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-04-08T02:00:00.000Z",
    "endAt": "2026-04-08T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/friend-to-friend-hangout/events/311899395/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-5ea75ad794",
    "slug": "claude-code-workshop-from-installation-to-building-apps-with-ai-level-01-5ea75ad",
    "title": "Claude Code Workshop: From Installation to Building Apps with AI Level 01",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳",
      "AI"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-05-15T02:00:00.000Z",
    "endAt": "2026-05-15T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/rocketone-ai-singapore/events/314541709/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-8c9fa51abd",
    "slug": "免费公益技术演讲-seo-小平-wordpress网站内链结构-8c9fa51abd",
    "title": "(免费公益技术演讲)SEO 小平:WordPress网站内链结构",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-04-08T02:00:00.000Z",
    "endAt": "2026-04-08T04:00:00.000Z",
    "priceType": "免费",
    "priceNote": "免费或公益",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/wordpress-meetup-shenzhen/events/314696490/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-41d165aca5",
    "slug": "waitlist-online-free-free-english-conversation-club-with-global-people-every-41d",
    "title": "Waitlist 🌎 (Online/Free) Free English Conversation Club with global people Every",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-04-04T02:00:00.000Z",
    "endAt": "2026-04-04T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/meetup-group-txqscvrf/events/314657550/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-05484a4a3a",
    "slug": "古迹铁路双语行-英语-普通话-05484a4a3a",
    "title": "古迹铁路双语行 (英语/普通话)",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-04-09T02:00:00.000Z",
    "endAt": "2026-04-09T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/discover-hong-kong-%E5%8F%91%E6%8E%98%E5%9C%A8%E6%B8%AF%E7%94%9F%E6%B4%BB%E7%9A%84%E7%BE%8E%E5%A5%BD/events/314641902/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-cb432f9a5a",
    "slug": "法律咨询-cb432f9a5a",
    "title": "法律咨询",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-05-19T02:00:00.000Z",
    "endAt": "2026-05-19T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11448",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-88a32e99e4",
    "slug": "南图双语故事会-presents-for-dad-88a32e99e4",
    "title": "南图双语故事会|Presents for Dad",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "读书沙龙",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-05-20T02:00:00.000Z",
    "endAt": "2026-05-20T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11423",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-12",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-58d94492f6",
    "slug": "心理咨询-58d94492f6",
    "title": "心理咨询",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-05-21T02:00:00.000Z",
    "endAt": "2026-05-21T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11444",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-c50bf6f4d4",
    "slug": "法律咨询-c50bf6f4d4",
    "title": "法律咨询",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-05-22T02:00:00.000Z",
    "endAt": "2026-05-22T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11447",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-c63777989e",
    "slug": "阅见南山-探索成长丨赤湾寻迹-海神-海防-海洋观-c63777989e",
    "title": "阅见南山·探索成长丨赤湾寻迹—海神、海防、海洋观",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-05-23T02:00:00.000Z",
    "endAt": "2026-05-23T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11426",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-luohu-library-events-cc344ebbb6",
    "slug": "绎说养生-云享罗图-骨质疏松的防治-用ai制作背景音乐-2026-03-26-cc344ebbb6",
    "title": "【绎说养生 云享罗图】骨质疏松的防治；用AI制作背景音乐 2026/03/26",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "罗湖图书馆活动速递",
      "AI"
    ],
    "district": "罗湖",
    "venue": "罗湖图书馆",
    "address": "罗湖图书馆",
    "startAt": "2026-03-26T02:00:00.000Z",
    "endAt": "2026-03-26T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szlhlib.org.cn/information/20427",
    "sourceId": "luohu-library-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-luohu-library-events-9d7be026f2",
    "slug": "真人图书馆-幸福家庭-健康人生-2026-03-26-9d7be026f2",
    "title": "【真人图书馆】幸福家庭 健康人生 2026/03/26",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "读书沙龙",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "罗湖图书馆活动速递"
    ],
    "district": "罗湖",
    "venue": "罗湖图书馆",
    "address": "罗湖图书馆",
    "startAt": "2026-03-26T02:00:00.000Z",
    "endAt": "2026-03-26T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szlhlib.org.cn/information/20426",
    "sourceId": "luohu-library-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-luohu-library-events-e99833bc60",
    "slug": "涂涂故事列车-星期三书店-今天我是一粒黄豆-2026-03-26-e99833bc60",
    "title": "【涂涂故事列车】《星期三书店》；《今天我是一粒黄豆》 2026/03/26",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "读书沙龙",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "罗湖图书馆活动速递"
    ],
    "district": "罗湖",
    "venue": "罗湖图书馆",
    "address": "罗湖图书馆",
    "startAt": "2026-03-26T02:00:00.000Z",
    "endAt": "2026-03-26T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szlhlib.org.cn/information/20425",
    "sourceId": "luohu-library-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-luohu-library-events-44f6a8cb68",
    "slug": "涂涂故事列车-创阅汇-白雪公主和77个小矮人-气象卫星模型制作-2026-03-01-44f6a8cb68",
    "title": "【涂涂故事列车 创阅汇】《白雪公主和77个小矮人》；气象卫星模型制作 2026/03/01",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "读书沙龙",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "罗湖图书馆活动速递"
    ],
    "district": "罗湖",
    "venue": "罗湖图书馆",
    "address": "罗湖图书馆",
    "startAt": "2026-03-01T02:00:00.000Z",
    "endAt": "2026-03-01T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szlhlib.org.cn/information/20367",
    "sourceId": "luohu-library-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-luohu-library-events-6d5c4f44fa",
    "slug": "妇女节主题活动-音乐-最美的精神之声-水彩体验-绘花-她之约-2026-03-01-6d5c4f44fa",
    "title": "【妇女节主题活动】音乐，最美的精神之声；水彩体验：绘花·她之约 2026/03/01",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "罗湖图书馆活动速递"
    ],
    "district": "罗湖",
    "venue": "罗湖图书馆",
    "address": "罗湖图书馆",
    "startAt": "2026-03-01T02:00:00.000Z",
    "endAt": "2026-03-01T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szlhlib.org.cn/information/20366",
    "sourceId": "luohu-library-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-5013cee00c",
    "slug": "同城讲堂第4季-人机协作的方法-系列本周讲座-5-11-5-15-5013cee00c",
    "title": "同城讲堂第4季：“人机协作的方法”系列本周讲座（5.11-5.15）",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "讲座阅读"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-05-11T16:00:00.000Z",
    "endAt": "2026-05-11T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.lib.szu.edu.cn/wp?url=http://info.lib.szu.edu.cn/infoliteracy/node/1015",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-542225082e",
    "slug": "2026年可知电子书21天阅读打卡季-参与即有机会赢得京东购物卡-542225082e",
    "title": "2026年可知电子书21天阅读打卡季，参与即有机会赢得京东购物卡！",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "读书沙龙",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "讲座阅读"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-05-10T16:00:00.000Z",
    "endAt": "2026-05-10T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.lib.szu.edu.cn/wp?url=http://info.lib.szu.edu.cn/infoliteracy/node/1016",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-1671fda3db",
    "slug": "同城讲堂第4季-人机协作的方法-系列下周讲座-5-6-5-8-1671fda3db",
    "title": "同城讲堂第4季：“人机协作的方法”系列下周讲座（5.6-5.8）",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "讲座阅读"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-05-05T16:00:00.000Z",
    "endAt": "2026-05-05T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.lib.szu.edu.cn/wp?url=http://info.lib.szu.edu.cn/infoliteracy/node/1012",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-d3dc20b545",
    "slug": "同城讲堂第4季-人机协作的方法-系列本周讲座-4-27-4-30-d3dc20b545",
    "title": "同城讲堂第4季：“人机协作的方法”系列本周讲座（4.27-4.30）",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "讲座阅读"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-04-27T16:00:00.000Z",
    "endAt": "2026-04-27T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.lib.szu.edu.cn/wp?url=http://info.lib.szu.edu.cn/infoliteracy/node/1008",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-d25776f54a",
    "slug": "书封解码大挑战-荔园读书人-快来猜书名赢好礼-d25776f54a",
    "title": "【书封解码大挑战】荔园读书人，快来猜书名赢好礼！",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "读书沙龙",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "讲座阅读"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-04-22T16:00:00.000Z",
    "endAt": "2026-04-22T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s?__biz=MzIyOTAyMDUxOQ==&tempkey=MTM3MF9TeUNzSkcrOGFBcWtDRCtnOThPakVOekxXRkJuelI0YU1QVjBXcEZsdzlOMG14S1JDU3g3MEVJX0t0YUtCSGYxQU9RUVU4S0VZZW5xdXJTYXdoRXdNeHEwd0RQN3NUYlU3aFYxOFROdFVFb2FWUmczV3RJZktCRzQ3V29QN2VYamYxVTNTWGFNSWNxTmttSlJLdFpqYmVDdGtHOXdlMjVDdUhMWXhBfn4%3D&chksm=f39423aac4e3aabc65524c6a5b0bf554e443c2dda62a9a29e1c5ef69ddd668646f66bd8dde86&token=1494154694&lang=zh_CN",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-c65500cdf5",
    "slug": "半导体设备-c65500cdf5",
    "title": "半导体设备",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-05-22T02:00:00.000Z",
    "endAt": "2026-05-22T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/2005573281005867009",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-62c34c8c99",
    "slug": "航空航天-62c34c8c99",
    "title": "航空航天",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-05-23T02:00:00.000Z",
    "endAt": "2026-05-23T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/2005566920071221250",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-76dbc5ae82",
    "slug": "新能源汽车-76dbc5ae82",
    "title": "新能源汽车",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-05-24T02:00:00.000Z",
    "endAt": "2026-05-24T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/1847563984212345000",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-69c5bd575d",
    "slug": "ai服务器-69c5bd575d",
    "title": "AI服务器",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动",
      "AI"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-05-13T02:00:00.000Z",
    "endAt": "2026-05-13T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/2005573499738820610",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-12",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-680df88f37",
    "slug": "具身智能-680df88f37",
    "title": "具身智能",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-05-14T02:00:00.000Z",
    "endAt": "2026-05-14T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/2005573624691331074",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-12",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-718a9f7de4",
    "slug": "美美与共-全国美术馆书法邀请展-718a9f7de4",
    "title": "美美与共——全国美术馆书法邀请展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动",
      "展会"
    ],
    "district": "福田",
    "venue": "何香凝美术馆7-8展厅",
    "address": "何香凝美术馆7-8展厅",
    "startAt": "2026-03-17T01:30:00.000Z",
    "endAt": "2026-03-17T03:30:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=a8fb4c9eb673440092febdddf17da31a",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-358dcd270c",
    "slug": "物外烟霞-20世纪中国风景画探索研究展-358dcd270c",
    "title": "物外烟霞——20世纪中国风景画探索研究展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动",
      "展会"
    ],
    "district": "福田",
    "venue": "何香凝美术馆1-6展厅",
    "address": "何香凝美术馆1-6展厅",
    "startAt": "2026-03-28T01:30:00.000Z",
    "endAt": "2026-03-28T03:30:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=05bffdcfeaf6486e87678595c7f59bd0",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-f35d00c299",
    "slug": "安德拉什-席夫爵士钢琴独奏音乐会-f35d00c299",
    "title": "安德拉什 席夫爵士钢琴独奏音乐会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动"
    ],
    "district": "福田",
    "venue": "深圳音乐厅二楼演奏大厅",
    "address": "深圳音乐厅二楼演奏大厅",
    "startAt": "2026-04-17T12:00:00.000Z",
    "endAt": "2026-04-17T14:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=fb7879e11bcd45cd8dca66a2f2c9ea98",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-66dc5ffbb9",
    "slug": "国画赏析活动-66dc5ffbb9",
    "title": "国画赏析活动",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动"
    ],
    "district": "福田",
    "venue": "深圳市罗湖区桂园街道办事处鸿翔花园7-A栋3楼书画室",
    "address": "深圳市罗湖区桂园街道办事处鸿翔花园7-A栋3楼书画室",
    "startAt": "2026-04-14T02:00:00.000Z",
    "endAt": "2026-04-14T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=07eea8ffbd4549d2b2383b8f0a658d67",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-079dc01115",
    "slug": "爵士热舞狂欢-解锁多巴胺爵士舞活动-4月14日19-30-20-30-079dc01115",
    "title": "爵士热舞狂欢，解锁多巴胺爵士舞活动（4月14日19：30-20：30）",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动"
    ],
    "district": "福田",
    "venue": "深圳市罗湖区翠竹街道办事处愉天社区综合文化服务中心",
    "address": "深圳市罗湖区翠竹街道办事处愉天社区综合文化服务中心",
    "startAt": "2026-04-14T02:00:00.000Z",
    "endAt": "2026-04-14T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=0d2750c83f054e15a3b83605742e76f4",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-childrens-palace-f6986d4d9c",
    "slug": "青少年科学艺术节-f6986d4d9c",
    "title": "青少年科学艺术节",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-05-20T02:00:00.000Z",
    "endAt": "2026-05-20T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szcp.com/Activity/sienceartfestival/",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": false
  },
  {
    "id": "live-shenzhen-childrens-palace-5b40042800",
    "slug": "鹏鹏科学秀-5b40042800",
    "title": "鹏鹏科学秀",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-05-21T02:00:00.000Z",
    "endAt": "2026-05-21T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szcp.com/Activity/sienceartfestival1/",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-childrens-palace-c7b4b12bc8",
    "slug": "艺术交流演出季-c7b4b12bc8",
    "title": "艺术交流演出季",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-05-22T02:00:00.000Z",
    "endAt": "2026-05-22T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szcp.com/Activity/artseason/",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-childrens-palace-15b818b583",
    "slug": "喜气羊羊过大年-深圳市少年宫欢度春节系列活动-15b818b583",
    "title": "喜气羊羊过大年-深圳市少年宫欢度春节系列活动",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-05-23T02:00:00.000Z",
    "endAt": "2026-05-23T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szcp.com/Activity/Goodhabit/2015/09/18/5924.html",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-childrens-palace-c7da4ac9eb",
    "slug": "少年宫-良好习惯伴我成长-系列活动之-争当快乐小雷锋-c7da4ac9eb",
    "title": "少年宫“良好习惯伴我成长”系列活动之——争当快乐小雷锋",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-05-24T02:00:00.000Z",
    "endAt": "2026-05-24T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szcp.com/Activity/Goodhabit/2010/04/21/2117.html",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-museum-events-212ce08a2f",
    "slug": "专题展览-212ce08a2f",
    "title": "专题展览",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳博物馆活动讲座",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳博物馆活动讲座",
    "address": "深圳博物馆活动讲座",
    "startAt": "2026-05-13T02:00:00.000Z",
    "endAt": "2026-05-13T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.shenzhenmuseum.com/exhibition/index",
    "sourceId": "shenzhen-museum-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-museum-events-2fcaf4c48d",
    "slug": "小讲解员-2fcaf4c48d",
    "title": "小讲解员",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳博物馆活动讲座"
    ],
    "district": "福田",
    "venue": "深圳博物馆活动讲座",
    "address": "深圳博物馆活动讲座",
    "startAt": "2026-05-14T02:00:00.000Z",
    "endAt": "2026-05-14T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.shenzhenmuseum.com/socialisation/index?type=socialisation&curIndex=2",
    "sourceId": "shenzhen-museum-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-museum-events-e3ef0208df",
    "slug": "活动讲座预约-e3ef0208df",
    "title": "活动讲座预约",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳博物馆活动讲座",
      "讲座阅读"
    ],
    "district": "福田",
    "venue": "深圳博物馆活动讲座",
    "address": "深圳博物馆活动讲座",
    "startAt": "2026-05-15T02:00:00.000Z",
    "endAt": "2026-05-15T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.shenzhenmuseum.com/socialisation/index?type=socialisation&curIndex=4",
    "sourceId": "shenzhen-museum-events",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-university-town-library-448b18844a",
    "slug": "展览速递-448b18844a",
    "title": "展览速递",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学城图书馆",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳大学城图书馆",
    "address": "深圳大学城图书馆",
    "startAt": "2026-05-16T02:00:00.000Z",
    "endAt": "2026-05-16T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.utszlib.edu.cn/exhibition/id-689.html?locale=zh_CN",
    "sourceId": "university-town-library",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-university-town-library-e54ead5efc",
    "slug": "数据库培训-e54ead5efc",
    "title": "数据库培训",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学城图书馆"
    ],
    "district": "福田",
    "venue": "深圳大学城图书馆",
    "address": "深圳大学城图书馆",
    "startAt": "2026-05-17T02:00:00.000Z",
    "endAt": "2026-05-17T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.utszlib.edu.cn/exhibition/id-690.html?locale=zh_CN",
    "sourceId": "university-town-library",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-university-town-library-5218d0aba5",
    "slug": "预约培训-5218d0aba5",
    "title": "预约培训",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学城图书馆"
    ],
    "district": "福田",
    "venue": "深圳大学城图书馆",
    "address": "深圳大学城图书馆",
    "startAt": "2026-05-18T02:00:00.000Z",
    "endAt": "2026-05-18T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.utszlib.edu.cn/newStudAppointment/id-988.html?locale=zh_CN",
    "sourceId": "university-town-library",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-university-town-library-a2072515b1",
    "slug": "迎新活动-a2072515b1",
    "title": "迎新活动",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学城图书馆"
    ],
    "district": "福田",
    "venue": "深圳大学城图书馆",
    "address": "深圳大学城图书馆",
    "startAt": "2026-05-19T02:00:00.000Z",
    "endAt": "2026-05-19T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.utszlib.edu.cn/page/id-992.html?locale=zh_CN",
    "sourceId": "university-town-library",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-university-town-library-6029003a7c",
    "slug": "2026-03-25-全城联动-让书回家-活动-6029003a7c",
    "title": "2026/03/25 “全城联动 让书回家”活动",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "读书沙龙",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学城图书馆"
    ],
    "district": "福田",
    "venue": "深圳大学城图书馆",
    "address": "深圳大学城图书馆",
    "startAt": "2026-03-25T02:00:00.000Z",
    "endAt": "2026-03-25T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.utszlib.edu.cn/article/view/id-20841.html?locale=zh_CN",
    "sourceId": "university-town-library",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-youth-activity-center-fa66f64bfb",
    "slug": "红领巾爱科学-元旦假期青少年人工智能公开课第三-fa66f64bfb",
    "title": "红领巾爱科学 | 元旦假期青少年人工智能公开课第三",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心",
      "AI"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-05-21T02:00:00.000Z",
    "endAt": "2026-05-21T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/s9vhTU9tUIuxgs5u6I54qw",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": false
  },
  {
    "id": "live-shenzhen-youth-activity-center-75589720a9",
    "slug": "亲子公益系列讲座五-智能时代成长力-未来人才的关-75589720a9",
    "title": "【亲子公益系列讲座五】智能时代成长力：未来人才的关",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心",
      "讲座阅读"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-05-22T02:00:00.000Z",
    "endAt": "2026-05-22T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "免费",
    "priceNote": "免费或公益",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/kPMQRop-F0Ql7aKTG5x8MA",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-youth-activity-center-73ee19ed79",
    "slug": "亲子公益系列讲座四-专注力与任务管理-孩子变身-73ee19ed79",
    "title": "【亲子公益系列讲座四】专注力与任务管理： 孩子变身",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心",
      "讲座阅读"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-05-23T02:00:00.000Z",
    "endAt": "2026-05-23T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "免费",
    "priceNote": "免费或公益",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/NUxu-9qjGrvq-PzR0Dipog",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-youth-activity-center-b75ca0e1dc",
    "slug": "亲子公益讲座-告别说教与对抗-让孩子主动改掉坏习-b75ca0e1dc",
    "title": "【亲子公益讲座】告别说教与对抗，让孩子主动改掉坏习",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心",
      "讲座阅读"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-05-24T02:00:00.000Z",
    "endAt": "2026-05-24T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "免费",
    "priceNote": "免费或公益",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/8ZevvOeCUHJki45MVPvmpw",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-youth-activity-center-79f9cb8230",
    "slug": "红领巾讲解员招募令丨传承红色基因-致敬改革先锋-79f9cb8230",
    "title": "红领巾讲解员招募令丨传承红色基因，致敬改革先锋",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-05-13T02:00:00.000Z",
    "endAt": "2026-05-13T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/UCezxHwFFxZEbzT20fltYg",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-1a479b24fe",
    "slug": "国际数字能源展-1a479b24fe",
    "title": "国际数字能源展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-14T02:00:00.000Z",
    "endAt": "2026-05-14T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.ideesz.com/",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-12",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-df516a522b",
    "slug": "深圳智慧养老展-df516a522b",
    "title": "深圳智慧养老展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-15T02:00:00.000Z",
    "endAt": "2026-05-15T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szwbzl.com/zdxm",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-12",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-7c5e5ecb17",
    "slug": "26-27赛季hyrox健身跑深圳站-7c5e5ecb17",
    "title": "26|27赛季HYROX健身跑深圳站",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-16T02:00:00.000Z",
    "endAt": "2026-05-16T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://hyrox.com/",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-dafc8843f4",
    "slug": "2026第三届深圳国际耳机展-dafc8843f4",
    "title": "2026第三届深圳国际耳机展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-17T02:00:00.000Z",
    "endAt": "2026-05-17T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.audioexpo.net/?news_12/=",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-12",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-6e11304279",
    "slug": "2026全球医疗健康展览会暨第四届深圳生殖医学健康大会-6e11304279",
    "title": "2026全球医疗健康展览会暨第四届深圳生殖医学健康大会",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-18T02:00:00.000Z",
    "endAt": "2026-05-18T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.nexpoworld.com/",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-12",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-cite-expo-bfac956f4c",
    "slug": "cite-中国电子信息博览会-bfac956f4c",
    "title": "CITE 中国电子信息博览会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "CITE 中国电子信息博览会"
    ],
    "district": "福田",
    "venue": "CITE 中国电子信息博览会",
    "address": "CITE 中国电子信息博览会",
    "startAt": "2026-04-09T02:00:00.000Z",
    "endAt": "2026-04-09T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.citexpo.org/about/introduction.html",
    "sourceId": "cite-expo",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-elexcon-shenzhen-1bab13c6ff",
    "slug": "elexcon-深圳国际电子展-1bab13c6ff",
    "title": "ELEXCON 深圳国际电子展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ELEXCON 深圳国际电子展",
      "展会"
    ],
    "district": "福田",
    "venue": "ELEXCON 深圳国际电子展",
    "address": "ELEXCON 深圳国际电子展",
    "startAt": "2026-01-16T02:00:00.000Z",
    "endAt": "2026-01-16T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://elexcon.com/en",
    "sourceId": "elexcon-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-eiotexpo-shenzhen-c011df998b",
    "slug": "e-iot-嵌入式与物联网展-c011df998b",
    "title": "E-IOT 嵌入式与物联网展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "E-IOT 嵌入式与物联网展",
      "展会"
    ],
    "district": "福田",
    "venue": "E-IOT 嵌入式与物联网展",
    "address": "E-IOT 嵌入式与物联网展",
    "startAt": "2026-08-26T02:00:00.000Z",
    "endAt": "2026-08-26T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.eiotexpo.com/",
    "sourceId": "eiotexpo-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-hackquest-shenzhen-hackathons-400b6bd7dd",
    "slug": "hackquest-深圳-hackathon-400b6bd7dd",
    "title": "HackQuest 深圳 Hackathon",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "Hackathon",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "HackQuest 深圳 Hackathon"
    ],
    "district": "福田",
    "venue": "HackQuest 深圳 Hackathon",
    "address": "HackQuest 深圳 Hackathon",
    "startAt": "2026-05-22T02:00:00.000Z",
    "endAt": "2026-05-22T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.hackquest.io/en/hackathons/AI-%C3%97-Web3-%E9%BB%91%E5%AE%A2%E6%9D%BE%E6%B7%B1%E5%9C%B3%E7%AB%99",
    "sourceId": "hackquest-shenzhen-hackathons",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-hackathonradar-shenzhen-b9d95095f9",
    "slug": "hackathonradar-深圳线索-b9d95095f9",
    "title": "HackathonRadar 深圳线索",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "Hackathon",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "HackathonRadar 深圳线索"
    ],
    "district": "福田",
    "venue": "HackathonRadar 深圳线索",
    "address": "HackathonRadar 深圳线索",
    "startAt": "2026-05-23T02:00:00.000Z",
    "endAt": "2026-05-23T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.hackathonradar.com/database/hackathon/9a9d9772-703e-4263-b163-c1f52cb784a8",
    "sourceId": "hackathonradar-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-sdcon-tech-conference-7afafb3bd1",
    "slug": "sdcon-技术大会-7afafb3bd1",
    "title": "SDCon 技术大会",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "SDCon 技术大会"
    ],
    "district": "福田",
    "venue": "SDCon 技术大会",
    "address": "SDCon 技术大会",
    "startAt": "2026-05-24T02:00:00.000Z",
    "endAt": "2026-05-24T04:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://sdcon.com.cn/",
    "sourceId": "sdcon-tech-conference",
    "lastConfirmedAt": "2026-05-12",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-iotexpo-shenzhen-6ede8976aa",
    "slug": "iote-深圳物联网展-6ede8976aa",
    "title": "IOTE 深圳物联网展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "IOTE 深圳物联网展",
      "展会"
    ],
    "district": "福田",
    "venue": "IOTE 深圳物联网展",
    "address": "IOTE 深圳物联网展",
    "startAt": "2020-07-31T02:00:00.000Z",
    "endAt": "2020-07-31T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.iotexpo.com.cn/sz/",
    "sourceId": "iotexpo-shenzhen",
    "lastConfirmedAt": "2026-05-12",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  }
] satisfies Activity[];
