import type { Activity } from "./types";

// Generated by scripts/collection/import-live-activities.mjs at 2026-05-14T14:16:18.626Z.
// Source report: /home/runner/work/City-Learning-Hub/City-Learning-Hub/docs/superpowers/reports/live-source-calibration-2026-05-14.json
export const liveCollectedActivities = [
  {
    "id": "live-shenzhen-conference-platform-1a479b24fe",
    "slug": "国际数字能源展-1a479b24fe",
    "title": "国际数字能源展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-15T10:00:00.000Z",
    "endAt": "2026-05-15T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.ideesz.com/",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-conference-platform-df516a522b",
    "slug": "深圳智慧养老展-df516a522b",
    "title": "深圳智慧养老展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-16T10:00:00.000Z",
    "endAt": "2026-05-16T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szwbzl.com/zdxm",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-conference-platform-7c5e5ecb17",
    "slug": "26-27赛季hyrox健身跑深圳站-7c5e5ecb17",
    "title": "26|27赛季HYROX健身跑深圳站",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-17T10:00:00.000Z",
    "endAt": "2026-05-17T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://hyrox.com/",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-conference-platform-dafc8843f4",
    "slug": "2026第三届深圳国际耳机展-dafc8843f4",
    "title": "2026第三届深圳国际耳机展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-18T10:00:00.000Z",
    "endAt": "2026-05-18T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.audioexpo.net/?news_12/=",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-conference-platform-6e11304279",
    "slug": "2026全球医疗健康展览会暨第四届深圳生殖医学健康大会-6e11304279",
    "title": "2026全球医疗健康展览会暨第四届深圳生殖医学健康大会",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-19T10:00:00.000Z",
    "endAt": "2026-05-19T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.nexpoworld.com/",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-743f56d91b",
    "slug": "枫丹乐影-张鼎萨克斯独奏音乐会-743f56d91b",
    "title": "《枫丹乐影》张鼎萨克斯独奏音乐会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-05-20T10:00:00.000Z",
    "endAt": "2026-05-20T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.douban.com/event/37826917/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-cee1087860",
    "slug": "陈明-等你爱我-2026深圳演唱会-cee1087860",
    "title": "陈明「等你爱我」2026深圳演唱会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-05-21T10:00:00.000Z",
    "endAt": "2026-05-21T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.douban.com/event/37843312/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-09bc5e4d88",
    "slug": "暑期带娃必体验-探索川剧变脸的奇妙世界-09bc5e4d88",
    "title": "暑期带娃必体验|探索川剧变脸的奇妙世界",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-05-22T10:00:00.000Z",
    "endAt": "2026-05-22T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.douban.com/event/37309570/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-3b8f35985b",
    "slug": "金声合唱团-文人情致-第5季-诗词散文合唱专场音乐会-3b8f35985b",
    "title": "金声合唱团“文人情致” 第5季-诗词散文合唱专场音乐会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-05-23T10:00:00.000Z",
    "endAt": "2026-05-23T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.douban.com/event/37840435/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-c482509c37",
    "slug": "齐豫-风采依旧-在深圳演唱会forever-splendor-live-concert-c482509c37",
    "title": "齐豫 风采依旧·在深圳演唱会FOREVER SPLENDOR LIVE CONCERT",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-05-24T10:00:00.000Z",
    "endAt": "2026-05-24T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.douban.com/event/37712040/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-dac710ff82",
    "slug": "杭州-ai-研习社第-01-期-2-小时-不写一行代码用-ai-做出惊艳的产品页面设计-dac710ff82",
    "title": "杭州 AI 研习社第 01 期：2 小时，不写一行代码用 AI 做出惊艳的产品页面设计",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动",
      "AI"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-05-25T10:00:00.000Z",
    "endAt": "2026-05-25T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/hang-zhou-ai-yan-xi-she-di-01-qi-2-xiao-shi-bu-xie-yi-hang-d",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-ca2f419aac",
    "slug": "赤道象限-年度-ai-创新峰会-与-300-家-ai-企业共同见证-ca2f419aac",
    "title": "赤道象限｜年度 AI 创新峰会，与 300 家 AI 企业共同见证",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动",
      "AI"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-05-26T10:00:00.000Z",
    "endAt": "2026-05-26T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/chi-dao-xiang-xian-nian-du-ai-chuang-xin-feng-hui-yu-300-jia",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-c439c5de46",
    "slug": "抢占-ai-搜索获客-跑赢-geo-时代-杭州站-c439c5de46",
    "title": "抢占 AI + 搜索获客，跑赢 GEO 时代 | 杭州站",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动",
      "AI"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-05-15T10:00:00.000Z",
    "endAt": "2026-05-15T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/qiang-zhan-ai-sou-suo-huo-ke-pao-ying-geo-shi-dai-hang-zhou",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-8a5cd14e69",
    "slug": "meet-ai-智航全球-ai-驱动下的出海实战研讨会-8a5cd14e69",
    "title": "MEET AI 智航全球——AI 驱动下的出海实战研讨会",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动",
      "AI"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-05-16T10:00:00.000Z",
    "endAt": "2026-05-16T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/meet-ai-zhi-hang-quan-qiu-ai-qu-dong-xia-de-chu-hai-shi-zhan",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-93d68cbee9",
    "slug": "所有人-2026-真的需要自己上手用-ai-了-中国-aigc-产业峰会-93d68cbee9",
    "title": "@所有人，2026 真的需要自己上手用 AI 了｜中国 AIGC 产业峰会",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动",
      "AI"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-05-17T10:00:00.000Z",
    "endAt": "2026-05-17T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/suo-you-ren-2026-zhen-de-xu-yao-zi-ji-shang-shou-yong-ai-lia",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-huodongxing-shenzhen-29c0872026",
    "slug": "agic2026深圳人工智能展-29c0872026",
    "title": "AGIC2026深圳人工智能展",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "活动行深圳",
      "AI",
      "展会"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-05-18T10:00:00.000Z",
    "endAt": "2026-05-18T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.huodongxing.com/event/5859922218300",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-huodongxing-shenzhen-7dd4429a26",
    "slug": "洞见变局-预见增长-跨境电商全链路经营实战沙龙-7dd4429a26",
    "title": "洞见变局 预见增长 —— 跨境电商全链路经营实战沙龙",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "活动行深圳"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-05-19T10:00:00.000Z",
    "endAt": "2026-05-19T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.huodongxing.com/event/6859921111300",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-huodongxing-shenzhen-dd74dd9770",
    "slug": "火热进行中-2026-ccee雨果跨境选品大会-dd74dd9770",
    "title": "【火热进行中】2026 CCEE雨果跨境选品大会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "活动行深圳"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-05-20T10:00:00.000Z",
    "endAt": "2026-05-20T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.huodongxing.com/event/8844211344400",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-huodongxing-shenzhen-2e14bc7a1d",
    "slug": "科创中国-创新创业投资大会-ai硬件专家终审会-2e14bc7a1d",
    "title": "“科创中国”创新创业投资大会——AI硬件专家终审会",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "活动行深圳",
      "AI"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-05-21T10:00:00.000Z",
    "endAt": "2026-05-21T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.huodongxing.com/event/5860741091100",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-huodongxing-shenzhen-89a379f80a",
    "slug": "ai驱动-跨境跃迁-26年ai赋能跨境电商创新峰会-89a379f80a",
    "title": "「AI驱动，跨境跃迁」26年AI赋能跨境电商创新峰会",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "活动行深圳",
      "AI"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-05-22T10:00:00.000Z",
    "endAt": "2026-05-22T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.huodongxing.com/event/7856454460100",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-60ae744b46",
    "slug": "whatsapp-group-for-event-updates-認識國際朋友-60ae744b46",
    "title": "WhatsApp group for event updates 認識國際朋友",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-04-08T10:00:00.000Z",
    "endAt": "2026-04-08T12:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/friend-to-friend-hangout/events/311899395/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-8c9fa51abd",
    "slug": "免费公益技术演讲-seo-小平-wordpress网站内链结构-8c9fa51abd",
    "title": "(免费公益技术演讲)SEO 小平:WordPress网站内链结构",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-04-08T10:00:00.000Z",
    "endAt": "2026-04-08T12:00:00.000Z",
    "priceType": "免费",
    "priceNote": "免费或公益",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/wordpress-meetup-shenzhen/events/314696490/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-5558420f84",
    "slug": "all-you-can-drink-beer-cha-chaan-teng-feast-5558420f84",
    "title": "All-You-Can-Drink Beer Cha Chaan Teng Feast",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-04-08T10:00:00.000Z",
    "endAt": "2026-04-08T12:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/friend-to-friend-hangout/events/314343885/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-05484a4a3a",
    "slug": "古迹铁路双语行-英语-普通话-05484a4a3a",
    "title": "古迹铁路双语行 (英语/普通话)",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-04-09T10:00:00.000Z",
    "endAt": "2026-04-09T12:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/discover-hong-kong-%E5%8F%91%E6%8E%98%E5%9C%A8%E6%B8%AF%E7%94%9F%E6%B4%BB%E7%9A%84%E7%BE%8E%E5%A5%BD/events/314641902/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-5ea75ad794",
    "slug": "claude-code-workshop-from-installation-to-building-apps-with-ai-level-01-5ea75ad",
    "title": "Claude Code Workshop: From Installation to Building Apps with AI Level 01",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳",
      "AI"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-05-15T10:00:00.000Z",
    "endAt": "2026-05-15T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/rocketone-ai-singapore/events/314541709/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-cb432f9a5a",
    "slug": "法律咨询-cb432f9a5a",
    "title": "法律咨询",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-05-16T10:00:00.000Z",
    "endAt": "2026-05-16T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11448",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-88a32e99e4",
    "slug": "南图双语故事会-presents-for-dad-88a32e99e4",
    "title": "南图双语故事会|Presents for Dad",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "读书沙龙",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-05-17T10:00:00.000Z",
    "endAt": "2026-05-17T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11423",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-14",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-58d94492f6",
    "slug": "心理咨询-58d94492f6",
    "title": "心理咨询",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-05-18T10:00:00.000Z",
    "endAt": "2026-05-18T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11444",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-c50bf6f4d4",
    "slug": "法律咨询-c50bf6f4d4",
    "title": "法律咨询",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-05-19T10:00:00.000Z",
    "endAt": "2026-05-19T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11447",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-c63777989e",
    "slug": "阅见南山-探索成长丨赤湾寻迹-海神-海防-海洋观-c63777989e",
    "title": "阅见南山·探索成长丨赤湾寻迹—海神、海防、海洋观",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-05-20T10:00:00.000Z",
    "endAt": "2026-05-20T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11426",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-db5810eb4d",
    "slug": "cell-press高级编辑讲座-科研写作-投稿通关秘籍来了-快来报名-db5810eb4d",
    "title": "Cell Press高级编辑讲座：科研写作+投稿通关秘籍来了！快来报名！",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "讲座阅读"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-05-13T16:00:00.000Z",
    "endAt": "2026-05-13T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.lib.szu.edu.cn/wp?url=http://info.lib.szu.edu.cn/infoliteracy/node/1019",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-5013cee00c",
    "slug": "同城讲堂第4季-人机协作的方法-系列本周讲座-5-11-5-15-5013cee00c",
    "title": "同城讲堂第4季：“人机协作的方法”系列本周讲座（5.11-5.15）",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "讲座阅读"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-05-11T16:00:00.000Z",
    "endAt": "2026-05-11T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.lib.szu.edu.cn/wp?url=http://info.lib.szu.edu.cn/infoliteracy/node/1015",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-542225082e",
    "slug": "2026年可知电子书21天阅读打卡季-参与即有机会赢得京东购物卡-542225082e",
    "title": "2026年可知电子书21天阅读打卡季，参与即有机会赢得京东购物卡！",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "读书沙龙",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "讲座阅读"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-05-10T16:00:00.000Z",
    "endAt": "2026-05-10T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.lib.szu.edu.cn/wp?url=http://info.lib.szu.edu.cn/infoliteracy/node/1016",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-1671fda3db",
    "slug": "同城讲堂第4季-人机协作的方法-系列下周讲座-5-6-5-8-1671fda3db",
    "title": "同城讲堂第4季：“人机协作的方法”系列下周讲座（5.6-5.8）",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "讲座阅读"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-05-05T16:00:00.000Z",
    "endAt": "2026-05-05T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.lib.szu.edu.cn/wp?url=http://info.lib.szu.edu.cn/infoliteracy/node/1012",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-11c307fe30",
    "slug": "重逢-最美的书-赴一场文字与设计的美学之约-中国-最美的书-专题书展启幕-11c307fe30",
    "title": "重逢 “最美的书”，赴一场文字与设计的美学之约 ——中国 “最美的书” 专题书展启幕",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "展会"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-04-29T16:00:00.000Z",
    "endAt": "2026-04-29T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/diWiwvMJWJYqUL_dgdHF2g?token=575127374&lang=zh_CN",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-c65500cdf5",
    "slug": "半导体设备-c65500cdf5",
    "title": "半导体设备",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-05-26T10:00:00.000Z",
    "endAt": "2026-05-26T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/2005573281005867009",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-62c34c8c99",
    "slug": "航空航天-62c34c8c99",
    "title": "航空航天",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-05-15T10:00:00.000Z",
    "endAt": "2026-05-15T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/2005566920071221250",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-76dbc5ae82",
    "slug": "新能源汽车-76dbc5ae82",
    "title": "新能源汽车",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-05-16T10:00:00.000Z",
    "endAt": "2026-05-16T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/1847563984212345000",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-69c5bd575d",
    "slug": "ai服务器-69c5bd575d",
    "title": "AI服务器",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动",
      "AI"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-05-17T10:00:00.000Z",
    "endAt": "2026-05-17T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/2005573499738820610",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-14",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-680df88f37",
    "slug": "具身智能-680df88f37",
    "title": "具身智能",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-05-18T10:00:00.000Z",
    "endAt": "2026-05-18T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/2005573624691331074",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-14",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-718a9f7de4",
    "slug": "美美与共-全国美术馆书法邀请展-718a9f7de4",
    "title": "美美与共——全国美术馆书法邀请展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动",
      "展会"
    ],
    "district": "福田",
    "venue": "何香凝美术馆7-8展厅",
    "address": "何香凝美术馆7-8展厅",
    "startAt": "2026-03-17T09:30:00.000Z",
    "endAt": "2026-03-17T11:30:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=a8fb4c9eb673440092febdddf17da31a",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-358dcd270c",
    "slug": "物外烟霞-20世纪中国风景画探索研究展-358dcd270c",
    "title": "物外烟霞——20世纪中国风景画探索研究展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动",
      "展会"
    ],
    "district": "福田",
    "venue": "何香凝美术馆1-6展厅",
    "address": "何香凝美术馆1-6展厅",
    "startAt": "2026-03-28T09:30:00.000Z",
    "endAt": "2026-03-28T11:30:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=05bffdcfeaf6486e87678595c7f59bd0",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-f35d00c299",
    "slug": "安德拉什-席夫爵士钢琴独奏音乐会-f35d00c299",
    "title": "安德拉什 席夫爵士钢琴独奏音乐会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动"
    ],
    "district": "福田",
    "venue": "深圳音乐厅二楼演奏大厅",
    "address": "深圳音乐厅二楼演奏大厅",
    "startAt": "2026-04-17T20:00:00.000Z",
    "endAt": "2026-04-17T22:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=fb7879e11bcd45cd8dca66a2f2c9ea98",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-66dc5ffbb9",
    "slug": "国画赏析活动-66dc5ffbb9",
    "title": "国画赏析活动",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动"
    ],
    "district": "福田",
    "venue": "深圳市罗湖区桂园街道办事处鸿翔花园7-A栋3楼书画室",
    "address": "深圳市罗湖区桂园街道办事处鸿翔花园7-A栋3楼书画室",
    "startAt": "2026-04-14T10:00:00.000Z",
    "endAt": "2026-04-14T12:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=07eea8ffbd4549d2b2383b8f0a658d67",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-079dc01115",
    "slug": "爵士热舞狂欢-解锁多巴胺爵士舞活动-4月14日19-30-20-30-079dc01115",
    "title": "爵士热舞狂欢，解锁多巴胺爵士舞活动（4月14日19：30-20：30）",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动"
    ],
    "district": "福田",
    "venue": "深圳市罗湖区翠竹街道办事处愉天社区综合文化服务中心",
    "address": "深圳市罗湖区翠竹街道办事处愉天社区综合文化服务中心",
    "startAt": "2026-04-14T10:00:00.000Z",
    "endAt": "2026-04-14T12:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=0d2750c83f054e15a3b83605742e76f4",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-childrens-palace-f6986d4d9c",
    "slug": "青少年科学艺术节-f6986d4d9c",
    "title": "青少年科学艺术节",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-05-24T10:00:00.000Z",
    "endAt": "2026-05-24T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szcp.com/Activity/sienceartfestival/",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": false
  },
  {
    "id": "live-shenzhen-childrens-palace-5b40042800",
    "slug": "鹏鹏科学秀-5b40042800",
    "title": "鹏鹏科学秀",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-05-25T10:00:00.000Z",
    "endAt": "2026-05-25T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szcp.com/Activity/sienceartfestival1/",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-childrens-palace-c7b4b12bc8",
    "slug": "艺术交流演出季-c7b4b12bc8",
    "title": "艺术交流演出季",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-05-26T10:00:00.000Z",
    "endAt": "2026-05-26T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szcp.com/Activity/artseason/",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-childrens-palace-15b818b583",
    "slug": "喜气羊羊过大年-深圳市少年宫欢度春节系列活动-15b818b583",
    "title": "喜气羊羊过大年-深圳市少年宫欢度春节系列活动",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-05-15T10:00:00.000Z",
    "endAt": "2026-05-15T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szcp.com/Activity/Goodhabit/2015/09/18/5924.html",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-childrens-palace-c7da4ac9eb",
    "slug": "少年宫-良好习惯伴我成长-系列活动之-争当快乐小雷锋-c7da4ac9eb",
    "title": "少年宫“良好习惯伴我成长”系列活动之——争当快乐小雷锋",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-05-16T10:00:00.000Z",
    "endAt": "2026-05-16T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szcp.com/Activity/Goodhabit/2010/04/21/2117.html",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-museum-events-212ce08a2f",
    "slug": "专题展览-212ce08a2f",
    "title": "专题展览",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳博物馆活动讲座",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳博物馆活动讲座",
    "address": "深圳博物馆活动讲座",
    "startAt": "2026-05-17T10:00:00.000Z",
    "endAt": "2026-05-17T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.shenzhenmuseum.com/exhibition/index",
    "sourceId": "shenzhen-museum-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-museum-events-2fcaf4c48d",
    "slug": "小讲解员-2fcaf4c48d",
    "title": "小讲解员",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳博物馆活动讲座"
    ],
    "district": "福田",
    "venue": "深圳博物馆活动讲座",
    "address": "深圳博物馆活动讲座",
    "startAt": "2026-05-18T10:00:00.000Z",
    "endAt": "2026-05-18T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.shenzhenmuseum.com/socialisation/index?type=socialisation&curIndex=2",
    "sourceId": "shenzhen-museum-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-museum-events-e3ef0208df",
    "slug": "活动讲座预约-e3ef0208df",
    "title": "活动讲座预约",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳博物馆活动讲座",
      "讲座阅读"
    ],
    "district": "福田",
    "venue": "深圳博物馆活动讲座",
    "address": "深圳博物馆活动讲座",
    "startAt": "2026-05-19T10:00:00.000Z",
    "endAt": "2026-05-19T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.shenzhenmuseum.com/socialisation/index?type=socialisation&curIndex=4",
    "sourceId": "shenzhen-museum-events",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-youth-activity-center-fa66f64bfb",
    "slug": "红领巾爱科学-元旦假期青少年人工智能公开课第三-fa66f64bfb",
    "title": "红领巾爱科学 | 元旦假期青少年人工智能公开课第三",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心",
      "AI"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-05-20T10:00:00.000Z",
    "endAt": "2026-05-20T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/s9vhTU9tUIuxgs5u6I54qw",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": false
  },
  {
    "id": "live-shenzhen-youth-activity-center-75589720a9",
    "slug": "亲子公益系列讲座五-智能时代成长力-未来人才的关-75589720a9",
    "title": "【亲子公益系列讲座五】智能时代成长力：未来人才的关",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心",
      "讲座阅读"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-05-21T10:00:00.000Z",
    "endAt": "2026-05-21T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "免费",
    "priceNote": "免费或公益",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/kPMQRop-F0Ql7aKTG5x8MA",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-youth-activity-center-73ee19ed79",
    "slug": "亲子公益系列讲座四-专注力与任务管理-孩子变身-73ee19ed79",
    "title": "【亲子公益系列讲座四】专注力与任务管理： 孩子变身",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心",
      "讲座阅读"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-05-22T10:00:00.000Z",
    "endAt": "2026-05-22T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "免费",
    "priceNote": "免费或公益",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/NUxu-9qjGrvq-PzR0Dipog",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-youth-activity-center-b75ca0e1dc",
    "slug": "亲子公益讲座-告别说教与对抗-让孩子主动改掉坏习-b75ca0e1dc",
    "title": "【亲子公益讲座】告别说教与对抗，让孩子主动改掉坏习",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心",
      "讲座阅读"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-05-23T10:00:00.000Z",
    "endAt": "2026-05-23T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "免费",
    "priceNote": "免费或公益",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/8ZevvOeCUHJki45MVPvmpw",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-youth-activity-center-79f9cb8230",
    "slug": "红领巾讲解员招募令丨传承红色基因-致敬改革先锋-79f9cb8230",
    "title": "红领巾讲解员招募令丨传承红色基因，致敬改革先锋",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-05-24T10:00:00.000Z",
    "endAt": "2026-05-24T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/UCezxHwFFxZEbzT20fltYg",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-1a479b24fe",
    "slug": "国际数字能源展-1a479b24fe",
    "title": "国际数字能源展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-25T10:00:00.000Z",
    "endAt": "2026-05-25T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.ideesz.com/",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-14",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-df516a522b",
    "slug": "深圳智慧养老展-df516a522b",
    "title": "深圳智慧养老展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-26T10:00:00.000Z",
    "endAt": "2026-05-26T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szwbzl.com/zdxm",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-14",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-7c5e5ecb17",
    "slug": "26-27赛季hyrox健身跑深圳站-7c5e5ecb17",
    "title": "26|27赛季HYROX健身跑深圳站",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-15T10:00:00.000Z",
    "endAt": "2026-05-15T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://hyrox.com/",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-dafc8843f4",
    "slug": "2026第三届深圳国际耳机展-dafc8843f4",
    "title": "2026第三届深圳国际耳机展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-16T10:00:00.000Z",
    "endAt": "2026-05-16T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.audioexpo.net/?news_12/=",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-14",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-6e11304279",
    "slug": "2026全球医疗健康展览会暨第四届深圳生殖医学健康大会-6e11304279",
    "title": "2026全球医疗健康展览会暨第四届深圳生殖医学健康大会",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-17T10:00:00.000Z",
    "endAt": "2026-05-17T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.nexpoworld.com/",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-14",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-cite-expo-bfac956f4c",
    "slug": "cite-中国电子信息博览会-bfac956f4c",
    "title": "CITE 中国电子信息博览会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "CITE 中国电子信息博览会"
    ],
    "district": "福田",
    "venue": "CITE 中国电子信息博览会",
    "address": "CITE 中国电子信息博览会",
    "startAt": "2026-04-09T02:00:00.000Z",
    "endAt": "2026-04-09T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.citexpo.org/about/introduction.html",
    "sourceId": "cite-expo",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-elexcon-shenzhen-1bab13c6ff",
    "slug": "elexcon-深圳国际电子展-1bab13c6ff",
    "title": "ELEXCON 深圳国际电子展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ELEXCON 深圳国际电子展",
      "展会"
    ],
    "district": "福田",
    "venue": "ELEXCON 深圳国际电子展",
    "address": "ELEXCON 深圳国际电子展",
    "startAt": "2026-01-16T02:00:00.000Z",
    "endAt": "2026-01-16T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://elexcon.com/en",
    "sourceId": "elexcon-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-eiotexpo-shenzhen-c011df998b",
    "slug": "e-iot-嵌入式与物联网展-c011df998b",
    "title": "E-IOT 嵌入式与物联网展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "E-IOT 嵌入式与物联网展",
      "展会"
    ],
    "district": "福田",
    "venue": "E-IOT 嵌入式与物联网展",
    "address": "E-IOT 嵌入式与物联网展",
    "startAt": "2026-08-26T02:00:00.000Z",
    "endAt": "2026-08-26T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.eiotexpo.com/",
    "sourceId": "eiotexpo-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "published",
    "weeklyFeatured": true,
    "childSafetyComplete": true
  },
  {
    "id": "live-hackquest-shenzhen-hackathons-400b6bd7dd",
    "slug": "hackquest-深圳-hackathon-400b6bd7dd",
    "title": "HackQuest 深圳 Hackathon",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "Hackathon",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "HackQuest 深圳 Hackathon"
    ],
    "district": "福田",
    "venue": "HackQuest 深圳 Hackathon",
    "address": "HackQuest 深圳 Hackathon",
    "startAt": "2026-05-21T10:00:00.000Z",
    "endAt": "2026-05-21T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.hackquest.io/en/hackathons/AI-%C3%97-Web3-%E9%BB%91%E5%AE%A2%E6%9D%BE%E6%B7%B1%E5%9C%B3%E7%AB%99",
    "sourceId": "hackquest-shenzhen-hackathons",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-hackathonradar-shenzhen-b9d95095f9",
    "slug": "hackathonradar-深圳线索-b9d95095f9",
    "title": "HackathonRadar 深圳线索",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "Hackathon",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "HackathonRadar 深圳线索"
    ],
    "district": "福田",
    "venue": "HackathonRadar 深圳线索",
    "address": "HackathonRadar 深圳线索",
    "startAt": "2026-05-22T10:00:00.000Z",
    "endAt": "2026-05-22T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.hackathonradar.com/database/hackathon/9a9d9772-703e-4263-b163-c1f52cb784a8",
    "sourceId": "hackathonradar-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-sdcon-tech-conference-7afafb3bd1",
    "slug": "sdcon-技术大会-7afafb3bd1",
    "title": "SDCon 技术大会",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "SDCon 技术大会"
    ],
    "district": "福田",
    "venue": "SDCon 技术大会",
    "address": "SDCon 技术大会",
    "startAt": "2026-05-23T10:00:00.000Z",
    "endAt": "2026-05-23T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://sdcon.com.cn/",
    "sourceId": "sdcon-tech-conference",
    "lastConfirmedAt": "2026-05-14",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-iotexpo-shenzhen-6ede8976aa",
    "slug": "iote-深圳物联网展-6ede8976aa",
    "title": "IOTE 深圳物联网展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "IOTE 深圳物联网展",
      "展会"
    ],
    "district": "福田",
    "venue": "IOTE 深圳物联网展",
    "address": "IOTE 深圳物联网展",
    "startAt": "2020-07-31T02:00:00.000Z",
    "endAt": "2020-07-31T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.iotexpo.com.cn/sz/",
    "sourceId": "iotexpo-shenzhen",
    "lastConfirmedAt": "2026-05-14",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  }
] satisfies Activity[];
