import type { Activity } from "./types";

// Generated by scripts/collection/import-live-activities.mjs at 2026-05-28T16:01:02.377Z.
// Source report: /home/runner/work/City-Learning-Hub/City-Learning-Hub/docs/superpowers/reports/live-source-calibration-2026-05-28.json
export const liveCollectedActivities = [
  {
    "id": "live-nanshan-tech-museum-991cd11e68",
    "slug": "深圳科学馆科普活动安排-991cd11e68",
    "title": "深圳科学馆科普活动安排",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳科学馆"
    ],
    "district": "福田",
    "venue": "深圳科学馆",
    "address": "深圳科学馆",
    "startAt": "2026-05-29T10:00:00.000Z",
    "endAt": "2026-05-29T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://szstm.com/mobile/html/gk/sj",
    "sourceId": "nanshan-tech-museum",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-book-city-ad22ced352",
    "slug": "当文化遇见ai-深圳出版集团携前沿科技亮相文博会-ad22ced352",
    "title": "当文化遇见AI：深圳出版集团携前沿科技亮相文博会",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳书城",
      "AI"
    ],
    "district": "福田",
    "venue": "深圳书城",
    "address": "深圳书城",
    "startAt": "2026-05-30T10:00:00.000Z",
    "endAt": "2026-05-30T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/ol653RM4ya5Z1_nGrhYTPw",
    "sourceId": "shenzhen-book-city",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "publicListingTier": "reference",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-book-city-51dd8f8174",
    "slug": "现实版-给阿嫲的情书-来了-百年侨批回批原件特展-重磅登陆湾区之眼-51dd8f8174",
    "title": "现实版“给阿嫲的情书”来了！百年侨批回批原件特展，重磅登陆湾区之眼！",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳书城",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳书城",
    "address": "深圳书城",
    "startAt": "2026-05-31T10:00:00.000Z",
    "endAt": "2026-05-31T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/Cdlj0BeyhRWQNf8_SSWNYA",
    "sourceId": "shenzhen-book-city",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "publicListingTier": "reference",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-book-city-7417c8d5e8",
    "slug": "深圳书城-习近平谈治国理政-第五卷已全面到货-7417c8d5e8",
    "title": "深圳书城《习近平谈治国理政》第五卷已全面到货！",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "读书沙龙",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳书城"
    ],
    "district": "福田",
    "venue": "深圳书城",
    "address": "深圳书城",
    "startAt": "2026-06-01T10:00:00.000Z",
    "endAt": "2026-06-01T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/GKqmJHjVs9tHEZsYe0qfzg",
    "sourceId": "shenzhen-book-city",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "publicListingTier": "reference",
    "publicScore": 89.4,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-book-city-f12926c00b",
    "slug": "好好玩-六一-乐园-深圳书城快乐上线-f12926c00b",
    "title": "好好玩“六一”乐园，深圳书城快乐上线！",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "读书沙龙",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳书城"
    ],
    "district": "福田",
    "venue": "深圳书城",
    "address": "深圳书城",
    "startAt": "2026-06-02T10:00:00.000Z",
    "endAt": "2026-06-02T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szbookmall.com/news/2242",
    "sourceId": "shenzhen-book-city",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "publicListingTier": "reference",
    "publicScore": 87.9,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-book-city-c991aa80dc",
    "slug": "深圳出版集团与深圳大剧院会员联动活动-c991aa80dc",
    "title": "深圳出版集团与深圳大剧院会员联动活动",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳书城"
    ],
    "district": "福田",
    "venue": "深圳书城",
    "address": "深圳书城",
    "startAt": "2026-06-03T10:00:00.000Z",
    "endAt": "2026-06-03T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szbookmall.com/news/2198",
    "sourceId": "shenzhen-book-city",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-tech-community-1c1456a30d",
    "slug": "autoresearch-systems-hackathon-with-modal-openai-raindrop-antler-1c1456a30d",
    "title": "Autoresearch Systems Hackathon with Modal, OpenAI, Raindrop & Antler",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "Hackathon",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳技术社区线索"
    ],
    "district": "福田",
    "venue": "深圳技术社区线索",
    "address": "深圳技术社区线索",
    "startAt": "2026-06-04T10:00:00.000Z",
    "endAt": "2026-06-04T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://lu.ma/fvz1h1dq",
    "sourceId": "tech-community",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-tech-community-65b5716f06",
    "slug": "technical-talk-with-thariq-shihipar-anthropic-65b5716f06",
    "title": "Technical Talk with Thariq Shihipar — Anthropic",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳技术社区线索"
    ],
    "district": "福田",
    "venue": "深圳技术社区线索",
    "address": "深圳技术社区线索",
    "startAt": "2026-06-05T10:00:00.000Z",
    "endAt": "2026-06-05T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://lu.ma/thariq-spc",
    "sourceId": "tech-community",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-conference-platform-1a479b24fe",
    "slug": "国际数字能源展-1a479b24fe",
    "title": "国际数字能源展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-06-06T10:00:00.000Z",
    "endAt": "2026-06-06T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.ideesz.com/",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "publicListingTier": "reference",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-conference-platform-df516a522b",
    "slug": "深圳智慧养老展-df516a522b",
    "title": "深圳智慧养老展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-06-07T10:00:00.000Z",
    "endAt": "2026-06-07T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szwbzl.com/zdxm",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "publicListingTier": "reference",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-conference-platform-dafc8843f4",
    "slug": "2026第三届深圳国际耳机展-dafc8843f4",
    "title": "2026第三届深圳国际耳机展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-06-08T10:00:00.000Z",
    "endAt": "2026-06-08T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.audioexpo.net/?news_12/=",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "publicListingTier": "reference",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-conference-platform-6e11304279",
    "slug": "2026全球医疗健康展览会暨第四届深圳生殖医学健康大会-6e11304279",
    "title": "2026全球医疗健康展览会暨第四届深圳生殖医学健康大会",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-06-09T10:00:00.000Z",
    "endAt": "2026-06-09T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.nexpoworld.com/",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "publicListingTier": "reference",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-conference-platform-7c5e5ecb17",
    "slug": "26-27赛季hyrox健身跑深圳站-7c5e5ecb17",
    "title": "26|27赛季HYROX健身跑深圳站",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-05-29T10:00:00.000Z",
    "endAt": "2026-05-29T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://hyrox.com/",
    "sourceId": "shenzhen-conference-platform",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-eventbrite-shenzhen-04048ac79e",
    "slug": "eventbrite-深圳线索页-04048ac79e",
    "title": "Eventbrite 深圳线索页",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Eventbrite 深圳"
    ],
    "district": "福田",
    "venue": "Eventbrite 深圳",
    "address": "Eventbrite 深圳",
    "startAt": "2026-05-30T10:00:00.000Z",
    "endAt": "2026-05-30T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.eventbrite.com/d/china--shenzhen/events/",
    "sourceId": "eventbrite-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-b440db0c2a",
    "slug": "张培力-仅存的诗意-b440db0c2a",
    "title": "张培力：仅存的诗意",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-05-31T10:00:00.000Z",
    "endAt": "2026-05-31T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.douban.com/event/37700473/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-615d5bbaab",
    "slug": "度假太阳系-太空探索乐园-615d5bbaab",
    "title": "度假太阳系 太空探索乐园",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-06-01T10:00:00.000Z",
    "endAt": "2026-06-01T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.douban.com/event/37576816/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-ead71238db",
    "slug": "源起华夏-月球冒险之旅-大型vr沉浸探索-ead71238db",
    "title": "《源起华夏 月球冒险之旅》大型VR沉浸探索",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-06-02T10:00:00.000Z",
    "endAt": "2026-06-02T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.douban.com/event/37309455/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-cee1087860",
    "slug": "陈明-等你爱我-2026深圳演唱会-cee1087860",
    "title": "陈明「等你爱我」2026深圳演唱会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-06-03T10:00:00.000Z",
    "endAt": "2026-06-03T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.douban.com/event/37843312/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-douban-shenzhen-743f56d91b",
    "slug": "枫丹乐影-张鼎萨克斯独奏音乐会-743f56d91b",
    "title": "《枫丹乐影》张鼎萨克斯独奏音乐会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "豆瓣同城深圳"
    ],
    "district": "福田",
    "venue": "豆瓣同城深圳",
    "address": "豆瓣同城深圳",
    "startAt": "2026-06-04T10:00:00.000Z",
    "endAt": "2026-06-04T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.douban.com/event/37826917/",
    "sourceId": "douban-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-908da80121",
    "slug": "成都周五-ai-夜话-开放麦线下沙龙-908da80121",
    "title": "成都周五 AI 夜话 · 开放麦线下沙龙",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动",
      "AI"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-06-05T10:00:00.000Z",
    "endAt": "2026-06-05T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/cheng-du-zhou-wu-ai-ye-hua-kai-fang-mai-xian-xia-sha-long",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-65d1d79fa0",
    "slug": "social-mixer-in-shenzhen-ai-硬件专场-65d1d79fa0",
    "title": "Social Mixer in ShenZhen | AI 硬件专场",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动",
      "AI"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-06-06T10:00:00.000Z",
    "endAt": "2026-06-06T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/social-mixer-in-shenzhen-ai-ying-jian-zhuan-chang",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-2ffa1a0d2b",
    "slug": "ai-数字人直播革命-告别真人-开启-24-小时全域增长-2ffa1a0d2b",
    "title": "AI 数字人直播革命：告别真人，开启 24 小时全域增长",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动",
      "AI"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-06-07T10:00:00.000Z",
    "endAt": "2026-06-07T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/ai-shu-zi-ren-zhi-bo-ge-ming-gao-bie-zhen-ren-kai-qi-24-xiao",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-d7cfedb3d4",
    "slug": "从计划到进化-ai-时代的领导力革命-d7cfedb3d4",
    "title": "从计划到进化：AI 时代的领导力革命",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动",
      "AI"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-06-08T10:00:00.000Z",
    "endAt": "2026-06-08T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/cong-ji-hua-dao-jin-hua-ai-shi-dai-de-ling-dao-li-ge-ming",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-lianpu-tech-events-298a289f96",
    "slug": "ai-nova-点火之夜-298a289f96",
    "title": "AI Nova 点火之夜",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "联谱科技活动",
      "AI"
    ],
    "district": "福田",
    "venue": "联谱科技活动",
    "address": "联谱科技活动",
    "startAt": "2026-06-09T10:00:00.000Z",
    "endAt": "2026-06-09T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://lianpu.com/event/ai-nova-dian-huo-zhi-ye",
    "sourceId": "lianpu-tech-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-huodongxing-shenzhen-9fc619896a",
    "slug": "高尔夫闭门私董会-一个-ip-一家上市公司-中腰部老板-ip-破局私董会-9fc619896a",
    "title": "【⛳️高尔夫闭门私董会】一个 IP = 一家上市公司｜中腰部老板 IP 破局私董会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "活动行深圳"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-05-29T10:00:00.000Z",
    "endAt": "2026-05-29T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.huodongxing.com/event/5862534192711",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-huodongxing-shenzhen-848706e95d",
    "slug": "szooia-助企强链-系列活动之-走进智立方集团-848706e95d",
    "title": "SZOOIA“助企强链”系列活动之—— 走进智立方集团",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "活动行深圳"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-05-30T10:00:00.000Z",
    "endAt": "2026-05-30T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.huodongxing.com/event/8862611841800",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-huodongxing-shenzhen-ec9f4c0db0",
    "slug": "高尔夫闭门私董会-百人老板企业用工风控实战营-ec9f4c0db0",
    "title": "【⛳️高尔夫闭门私董会】百人老板企业用工风控实战营",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "活动行深圳"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-05-31T10:00:00.000Z",
    "endAt": "2026-05-31T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.huodongxing.com/event/4862521404811",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-huodongxing-shenzhen-61d058e83d",
    "slug": "深圳-crs合规时代-如何守住全球资产-61d058e83d",
    "title": "深圳 | CRS合规时代，如何守住全球资产？",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "活动行深圳"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-06-01T10:00:00.000Z",
    "endAt": "2026-06-01T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.huodongxing.com/event/3860776294800",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-huodongxing-shenzhen-f8219ba82e",
    "slug": "深圳线下-心经大智慧分享-f8219ba82e",
    "title": "【深圳线下】心经大智慧分享",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "活动行深圳"
    ],
    "district": "福田",
    "venue": "活动行深圳",
    "address": "活动行深圳",
    "startAt": "2026-06-02T10:00:00.000Z",
    "endAt": "2026-06-02T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.huodongxing.com/event/2861933090800",
    "sourceId": "huodongxing-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-60ae744b46",
    "slug": "whatsapp-group-for-event-updates-認識國際朋友-60ae744b46",
    "title": "WhatsApp group for event updates 認識國際朋友",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-04-08T10:00:00.000Z",
    "endAt": "2026-04-08T12:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/friend-to-friend-hangout/events/311899395/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-318065ecf1",
    "slug": "hike-wong-shek-pier-to-sai-wan-pavilion-318065ecf1",
    "title": "Hike: Wong Shek Pier to Sai Wan Pavilion",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-04-09T10:00:00.000Z",
    "endAt": "2026-04-09T12:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/longitude-latitude/events/314874421/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-bffba939df",
    "slug": "china-beyond-life-trade-shenzhen-bffba939df",
    "title": "China & Beyond: Life & Trade (Shenzhen)",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-06-05T10:00:00.000Z",
    "endAt": "2026-06-05T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/china-europe-business-life-exchange/events/314945432/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-05b50364a0",
    "slug": "waitlist-ma-shi-chau-trail-05b50364a0",
    "title": "Waitlist Ma Shi Chau Trail 🥾",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-04-08T10:00:00.000Z",
    "endAt": "2026-04-08T12:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/hikentrail-adventures/events/314943857/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-meetup-shenzhen-ad654ac3c3",
    "slug": "waitlist-深圳龍華區觀瀾古墟導賞一日遊-ad654ac3c3",
    "title": "Waitlist 🛖深圳龍華區觀瀾古墟導賞一日遊🇨🇳",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Meetup 深圳"
    ],
    "district": "福田",
    "venue": "Meetup 深圳",
    "address": "Meetup 深圳",
    "startAt": "2026-04-05T10:00:00.000Z",
    "endAt": "2026-04-05T12:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.meetup.com/historic-site-tour-%E6%B8%AF%E9%81%BA%E8%B9%9F-%E6%8E%A2%E7%B4%A2-%E5%B0%88%E9%A1%8C%E5%82%BE%E8%AB%87%E7%BE%A4%E7%B5%84-shenzhen-hiking/events/314764243/",
    "sourceId": "meetup-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-4fe4a759de",
    "slug": "馆员故事会-线上分享-五月五-过端午-4fe4a759de",
    "title": "【馆员故事会】线上分享|《五月五 过端午》",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "读书沙龙",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-06-08T10:00:00.000Z",
    "endAt": "2026-06-08T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11530",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-28",
    "status": "published",
    "weeklyFeatured": true,
    "publicListingTier": "featured",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-9f5e87974b",
    "slug": "走进图书馆丨-马背上的女图书馆员-9f5e87974b",
    "title": "走进图书馆丨《马背上的女图书馆员》",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "读书沙龙",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-06-09T10:00:00.000Z",
    "endAt": "2026-06-09T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11521",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-28",
    "status": "published",
    "weeklyFeatured": true,
    "publicListingTier": "featured",
    "publicScore": 95.2,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-92cd2ba7bf",
    "slug": "跟名师读名著系列丨再读-时代广场的蟋蟀-92cd2ba7bf",
    "title": "跟名师读名著系列丨再读《时代广场的蟋蟀》",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-05-29T10:00:00.000Z",
    "endAt": "2026-05-29T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11526",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-38b4cb7ef6",
    "slug": "心理咨询-38b4cb7ef6",
    "title": "心理咨询",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-05-30T10:00:00.000Z",
    "endAt": "2026-05-30T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11534",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-nanshan-library-activities-131fe47ae4",
    "slug": "法律咨询-131fe47ae4",
    "title": "法律咨询",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "南山图书馆活动平台"
    ],
    "district": "南山",
    "venue": "南山图书馆",
    "address": "南山图书馆",
    "startAt": "2026-05-31T10:00:00.000Z",
    "endAt": "2026-05-31T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://activity.nslib.cn/activity/info/11537",
    "sourceId": "nanshan-library-activities",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-2f74831428",
    "slug": "同城讲堂第4季-人机协作的方法-系列本周讲座-5-25-5-29-2f74831428",
    "title": "同城讲堂第4季：“人机协作的方法”系列本周讲座（5.25-5.29）",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "讲座阅读"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-05-24T16:00:00.000Z",
    "endAt": "2026-05-24T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.lib.szu.edu.cn/wp?url=http://info.lib.szu.edu.cn/infoliteracy/node/1025",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-a061517fdc",
    "slug": "同城讲堂第4季-人机协作的方法-系列本周讲座-5-18-5-22-a061517fdc",
    "title": "同城讲堂第4季：“人机协作的方法”系列本周讲座（5.18-5.22）",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "讲座阅读"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-05-17T16:00:00.000Z",
    "endAt": "2026-05-17T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.lib.szu.edu.cn/wp?url=http://info.lib.szu.edu.cn/infoliteracy/node/1020",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-db5810eb4d",
    "slug": "cell-press高级编辑讲座-科研写作-投稿通关秘籍来了-快来报名-db5810eb4d",
    "title": "Cell Press高级编辑讲座：科研写作+投稿通关秘籍来了！快来报名！",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "讲座阅读"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-05-13T16:00:00.000Z",
    "endAt": "2026-05-13T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.lib.szu.edu.cn/wp?url=http://info.lib.szu.edu.cn/infoliteracy/node/1019",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-5013cee00c",
    "slug": "同城讲堂第4季-人机协作的方法-系列本周讲座-5-11-5-15-5013cee00c",
    "title": "同城讲堂第4季：“人机协作的方法”系列本周讲座（5.11-5.15）",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "讲座阅读"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-05-11T16:00:00.000Z",
    "endAt": "2026-05-11T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.lib.szu.edu.cn/wp?url=http://info.lib.szu.edu.cn/infoliteracy/node/1015",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szu-library-events-542225082e",
    "slug": "2026年可知电子书21天阅读打卡季-参与即有机会赢得京东购物卡-542225082e",
    "title": "2026年可知电子书21天阅读打卡季，参与即有机会赢得京东购物卡！",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "读书沙龙",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学图书馆活动",
      "讲座阅读"
    ],
    "district": "南山",
    "venue": "深圳大学图书馆",
    "address": "深圳大学图书馆",
    "startAt": "2026-05-10T16:00:00.000Z",
    "endAt": "2026-05-10T18:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.lib.szu.edu.cn/wp?url=http://info.lib.szu.edu.cn/infoliteracy/node/1016",
    "sourceId": "szu-library-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-69c5bd575d",
    "slug": "ai服务器-69c5bd575d",
    "title": "AI服务器",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动",
      "AI"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-06-06T10:00:00.000Z",
    "endAt": "2026-06-06T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/2005573499738820610",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-28",
    "status": "published",
    "weeklyFeatured": true,
    "publicListingTier": "featured",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-680df88f37",
    "slug": "具身智能-680df88f37",
    "title": "具身智能",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-06-07T10:00:00.000Z",
    "endAt": "2026-06-07T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/2005573624691331074",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-28",
    "status": "published",
    "weeklyFeatured": true,
    "publicListingTier": "featured",
    "publicScore": 92.5,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-c65500cdf5",
    "slug": "半导体设备-c65500cdf5",
    "title": "半导体设备",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-06-08T10:00:00.000Z",
    "endAt": "2026-06-08T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/2005573281005867009",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-62c34c8c99",
    "slug": "航空航天-62c34c8c99",
    "title": "航空航天",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-06-09T10:00:00.000Z",
    "endAt": "2026-06-09T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/2005566920071221250",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-ites-meetings-76dbc5ae82",
    "slug": "新能源汽车-76dbc5ae82",
    "title": "新能源汽车",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ITES 深圳工业展会议活动"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心",
    "address": "深圳国际会展中心",
    "startAt": "2026-05-29T10:00:00.000Z",
    "endAt": "2026-05-29T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.iteschina.com/zh-cn/meeting/1847563984212345000",
    "sourceId": "ites-meetings",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-718a9f7de4",
    "slug": "美美与共-全国美术馆书法邀请展-718a9f7de4",
    "title": "美美与共——全国美术馆书法邀请展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动",
      "展会"
    ],
    "district": "福田",
    "venue": "何香凝美术馆7-8展厅",
    "address": "何香凝美术馆7-8展厅",
    "startAt": "2026-03-17T09:30:00.000Z",
    "endAt": "2026-03-17T11:30:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=a8fb4c9eb673440092febdddf17da31a",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-358dcd270c",
    "slug": "物外烟霞-20世纪中国风景画探索研究展-358dcd270c",
    "title": "物外烟霞——20世纪中国风景画探索研究展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动",
      "展会"
    ],
    "district": "福田",
    "venue": "何香凝美术馆1-6展厅",
    "address": "何香凝美术馆1-6展厅",
    "startAt": "2026-03-28T09:30:00.000Z",
    "endAt": "2026-03-28T11:30:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=05bffdcfeaf6486e87678595c7f59bd0",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-079dc01115",
    "slug": "爵士热舞狂欢-解锁多巴胺爵士舞活动-4月14日19-30-20-30-079dc01115",
    "title": "爵士热舞狂欢，解锁多巴胺爵士舞活动（4月14日19：30-20：30）",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动"
    ],
    "district": "福田",
    "venue": "深圳市罗湖区翠竹街道办事处愉天社区综合文化服务中心",
    "address": "深圳市罗湖区翠竹街道办事处愉天社区综合文化服务中心",
    "startAt": "2026-04-14T10:00:00.000Z",
    "endAt": "2026-04-14T12:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=0d2750c83f054e15a3b83605742e76f4",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-66dc5ffbb9",
    "slug": "国画赏析活动-66dc5ffbb9",
    "title": "国画赏析活动",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动"
    ],
    "district": "福田",
    "venue": "深圳市罗湖区桂园街道办事处鸿翔花园7-A栋3楼书画室",
    "address": "深圳市罗湖区桂园街道办事处鸿翔花园7-A栋3楼书画室",
    "startAt": "2026-04-14T10:00:00.000Z",
    "endAt": "2026-04-14T12:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=07eea8ffbd4549d2b2383b8f0a658d67",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szwen-cultural-events-f35d00c299",
    "slug": "安德拉什-席夫爵士钢琴独奏音乐会-f35d00c299",
    "title": "安德拉什 席夫爵士钢琴独奏音乐会",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳文体通活动"
    ],
    "district": "福田",
    "venue": "深圳音乐厅二楼演奏大厅",
    "address": "深圳音乐厅二楼演奏大厅",
    "startAt": "2026-04-17T20:00:00.000Z",
    "endAt": "2026-04-17T22:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szwen.cn/eventDetail?id=fb7879e11bcd45cd8dca66a2f2c9ea98",
    "sourceId": "szwen-cultural-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-childrens-palace-f6986d4d9c",
    "slug": "青少年科学艺术节-f6986d4d9c",
    "title": "青少年科学艺术节",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-06-04T10:00:00.000Z",
    "endAt": "2026-06-04T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szcp.com/Activity/sienceartfestival/",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "publicListingTier": "reference",
    "publicScore": 89,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-childrens-palace-5b40042800",
    "slug": "鹏鹏科学秀-5b40042800",
    "title": "鹏鹏科学秀",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-06-05T10:00:00.000Z",
    "endAt": "2026-06-05T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szcp.com/Activity/sienceartfestival1/",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "publicListingTier": "reference",
    "publicScore": 89,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-childrens-palace-c7da4ac9eb",
    "slug": "少年宫-良好习惯伴我成长-系列活动之-争当快乐小雷锋-c7da4ac9eb",
    "title": "少年宫“良好习惯伴我成长”系列活动之——争当快乐小雷锋",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-06-06T10:00:00.000Z",
    "endAt": "2026-06-06T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szcp.com/Activity/Goodhabit/2010/04/21/2117.html",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-childrens-palace-15b818b583",
    "slug": "喜气羊羊过大年-深圳市少年宫欢度春节系列活动-15b818b583",
    "title": "喜气羊羊过大年-深圳市少年宫欢度春节系列活动",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-06-07T10:00:00.000Z",
    "endAt": "2026-06-07T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szcp.com/Activity/Goodhabit/2015/09/18/5924.html",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-childrens-palace-c7b4b12bc8",
    "slug": "艺术交流演出季-c7b4b12bc8",
    "title": "艺术交流演出季",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市少年宫主题活动"
    ],
    "district": "福田",
    "venue": "深圳市少年宫主题活动",
    "address": "深圳市少年宫主题活动",
    "startAt": "2026-06-08T10:00:00.000Z",
    "endAt": "2026-06-08T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.szcp.com/Activity/artseason/",
    "sourceId": "shenzhen-childrens-palace",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-science-museum-991cd11e68",
    "slug": "深圳科学馆科普活动安排-991cd11e68",
    "title": "深圳科学馆科普活动安排",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳科学馆"
    ],
    "district": "福田",
    "venue": "深圳科学馆",
    "address": "深圳科学馆",
    "startAt": "2026-06-09T10:00:00.000Z",
    "endAt": "2026-06-09T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://szstm.com/mobile/html/gk/sj",
    "sourceId": "shenzhen-science-museum",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-museum-events-212ce08a2f",
    "slug": "专题展览-212ce08a2f",
    "title": "专题展览",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳博物馆活动讲座",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳博物馆活动讲座",
    "address": "深圳博物馆活动讲座",
    "startAt": "2026-05-29T10:00:00.000Z",
    "endAt": "2026-05-29T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.shenzhenmuseum.com/exhibition/index",
    "sourceId": "shenzhen-museum-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-museum-events-e3ef0208df",
    "slug": "活动讲座预约-e3ef0208df",
    "title": "活动讲座预约",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳博物馆活动讲座",
      "讲座阅读"
    ],
    "district": "福田",
    "venue": "深圳博物馆活动讲座",
    "address": "深圳博物馆活动讲座",
    "startAt": "2026-05-30T10:00:00.000Z",
    "endAt": "2026-05-30T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.shenzhenmuseum.com/socialisation/index?type=socialisation&curIndex=4",
    "sourceId": "shenzhen-museum-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-museum-events-2fcaf4c48d",
    "slug": "小讲解员-2fcaf4c48d",
    "title": "小讲解员",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳博物馆活动讲座"
    ],
    "district": "福田",
    "venue": "深圳博物馆活动讲座",
    "address": "深圳博物馆活动讲座",
    "startAt": "2026-05-31T10:00:00.000Z",
    "endAt": "2026-05-31T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.shenzhenmuseum.com/socialisation/index?type=socialisation&curIndex=2",
    "sourceId": "shenzhen-museum-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-university-town-library-6029003a7c",
    "slug": "2026-03-25-全城联动-让书回家-活动-6029003a7c",
    "title": "2026/03/25 “全城联动 让书回家”活动",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "读书沙龙",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学城图书馆"
    ],
    "district": "福田",
    "venue": "深圳大学城图书馆",
    "address": "深圳大学城图书馆",
    "startAt": "2026-03-25T10:00:00.000Z",
    "endAt": "2026-03-25T12:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.utszlib.edu.cn/article/view/id-20841.html?locale=zh_CN",
    "sourceId": "university-town-library",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-university-town-library-448b18844a",
    "slug": "展览速递-448b18844a",
    "title": "展览速递",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学城图书馆",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳大学城图书馆",
    "address": "深圳大学城图书馆",
    "startAt": "2026-06-02T10:00:00.000Z",
    "endAt": "2026-06-02T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.utszlib.edu.cn/exhibition/id-689.html?locale=zh_CN",
    "sourceId": "university-town-library",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-university-town-library-a2072515b1",
    "slug": "迎新活动-a2072515b1",
    "title": "迎新活动",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学城图书馆"
    ],
    "district": "福田",
    "venue": "深圳大学城图书馆",
    "address": "深圳大学城图书馆",
    "startAt": "2026-06-03T10:00:00.000Z",
    "endAt": "2026-06-03T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.utszlib.edu.cn/page/id-992.html?locale=zh_CN",
    "sourceId": "university-town-library",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-university-town-library-e54ead5efc",
    "slug": "数据库培训-e54ead5efc",
    "title": "数据库培训",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学城图书馆"
    ],
    "district": "福田",
    "venue": "深圳大学城图书馆",
    "address": "深圳大学城图书馆",
    "startAt": "2026-06-04T10:00:00.000Z",
    "endAt": "2026-06-04T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.utszlib.edu.cn/exhibition/id-690.html?locale=zh_CN",
    "sourceId": "university-town-library",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-university-town-library-5218d0aba5",
    "slug": "预约培训-5218d0aba5",
    "title": "预约培训",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳大学城图书馆"
    ],
    "district": "福田",
    "venue": "深圳大学城图书馆",
    "address": "深圳大学城图书馆",
    "startAt": "2026-06-05T10:00:00.000Z",
    "endAt": "2026-06-05T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.utszlib.edu.cn/newStudAppointment/id-988.html?locale=zh_CN",
    "sourceId": "university-town-library",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-redcube-events-631798ab54",
    "slug": "深圳红立方文化活动-631798ab54",
    "title": "深圳红立方文化活动",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳红立方文化活动"
    ],
    "district": "福田",
    "venue": "深圳红立方文化活动",
    "address": "深圳红立方文化活动",
    "startAt": "2026-06-06T10:00:00.000Z",
    "endAt": "2026-06-06T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://www.sz-redcube.com/",
    "sourceId": "shenzhen-redcube-events",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-youth-activity-center-fa66f64bfb",
    "slug": "红领巾爱科学-元旦假期青少年人工智能公开课第三-fa66f64bfb",
    "title": "红领巾爱科学 | 元旦假期青少年人工智能公开课第三",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心",
      "AI"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-06-07T10:00:00.000Z",
    "endAt": "2026-06-07T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/s9vhTU9tUIuxgs5u6I54qw",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "publicListingTier": "reference",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-youth-activity-center-75589720a9",
    "slug": "亲子公益系列讲座五-智能时代成长力-未来人才的关-75589720a9",
    "title": "【亲子公益系列讲座五】智能时代成长力：未来人才的关",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心",
      "讲座阅读"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-06-08T10:00:00.000Z",
    "endAt": "2026-06-08T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "免费",
    "priceNote": "免费或公益",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/kPMQRop-F0Ql7aKTG5x8MA",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "publicListingTier": "reference",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-youth-activity-center-73ee19ed79",
    "slug": "亲子公益系列讲座四-专注力与任务管理-孩子变身-73ee19ed79",
    "title": "【亲子公益系列讲座四】专注力与任务管理： 孩子变身",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心",
      "讲座阅读"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-06-09T10:00:00.000Z",
    "endAt": "2026-06-09T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "免费",
    "priceNote": "免费或公益",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/NUxu-9qjGrvq-PzR0Dipog",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "publicListingTier": "reference",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-youth-activity-center-b75ca0e1dc",
    "slug": "亲子公益讲座-告别说教与对抗-让孩子主动改掉坏习-b75ca0e1dc",
    "title": "【亲子公益讲座】告别说教与对抗，让孩子主动改掉坏习",
    "summary": "讲座阅读类活动，适合安排轻量学习。",
    "category": "社科讲座",
    "audience": [
      "family"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心",
      "讲座阅读"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-05-29T10:00:00.000Z",
    "endAt": "2026-05-29T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "免费",
    "priceNote": "免费或公益",
    "reservationRequired": true,
    "ageBand": "见活动页",
    "difficulty": "入门",
    "recommendation": "适合想听讲座、读书或参加公共文化活动的人。",
    "bestFor": "适合亲子家庭，出发前请核对年龄和陪同要求。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/8ZevvOeCUHJki45MVPvmpw",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "publicListingTier": "reference",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-youth-activity-center-79f9cb8230",
    "slug": "红领巾讲解员招募令丨传承红色基因-致敬改革先锋-79f9cb8230",
    "title": "红领巾讲解员招募令丨传承红色基因，致敬改革先锋",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳市青少年活动中心"
    ],
    "district": "福田",
    "venue": "深圳市青少年活动中心",
    "address": "深圳市青少年活动中心",
    "startAt": "2026-05-30T10:00:00.000Z",
    "endAt": "2026-05-30T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://mp.weixin.qq.com/s/UCezxHwFFxZEbzT20fltYg",
    "sourceId": "shenzhen-youth-activity-center",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-shenzhen-world-schedule-d2b0b76222",
    "slug": "深圳国际会展中心排期-d2b0b76222",
    "title": "深圳国际会展中心排期",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳国际会展中心排期",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳国际会展中心排期",
    "address": "深圳国际会展中心排期",
    "startAt": "2026-05-31T10:00:00.000Z",
    "endAt": "2026-05-31T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.shenzhen-world.com/scheduling/index.html",
    "sourceId": "shenzhen-world-schedule",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-1a479b24fe",
    "slug": "国际数字能源展-1a479b24fe",
    "title": "国际数字能源展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-06-01T10:00:00.000Z",
    "endAt": "2026-06-01T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.ideesz.com/",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-28",
    "status": "published",
    "weeklyFeatured": true,
    "publicListingTier": "featured",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-df516a522b",
    "slug": "深圳智慧养老展-df516a522b",
    "title": "深圳智慧养老展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-06-02T10:00:00.000Z",
    "endAt": "2026-06-02T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.szwbzl.com/zdxm",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-28",
    "status": "published",
    "weeklyFeatured": true,
    "publicListingTier": "featured",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-dafc8843f4",
    "slug": "2026第三届深圳国际耳机展-dafc8843f4",
    "title": "2026第三届深圳国际耳机展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-06-03T10:00:00.000Z",
    "endAt": "2026-06-03T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "http://www.audioexpo.net/?news_12/=",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-28",
    "status": "published",
    "weeklyFeatured": true,
    "publicListingTier": "featured",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-6e11304279",
    "slug": "2026全球医疗健康展览会暨第四届深圳生殖医学健康大会-6e11304279",
    "title": "2026全球医疗健康展览会暨第四届深圳生殖医学健康大会",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会",
      "展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-06-04T10:00:00.000Z",
    "endAt": "2026-06-04T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.nexpoworld.com/",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-28",
    "status": "published",
    "weeklyFeatured": true,
    "publicListingTier": "featured",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-szcec-futian-schedule-7c5e5ecb17",
    "slug": "26-27赛季hyrox健身跑深圳站-7c5e5ecb17",
    "title": "26|27赛季HYROX健身跑深圳站",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "深圳会展中心近期展会"
    ],
    "district": "福田",
    "venue": "深圳会展中心近期展会",
    "address": "深圳会展中心近期展会",
    "startAt": "2026-06-05T10:00:00.000Z",
    "endAt": "2026-06-05T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://hyrox.com/",
    "sourceId": "szcec-futian-schedule",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-elexcon-shenzhen-1bab13c6ff",
    "slug": "elexcon-深圳国际电子展-1bab13c6ff",
    "title": "ELEXCON 深圳国际电子展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "ELEXCON 深圳国际电子展",
      "展会"
    ],
    "district": "福田",
    "venue": "ELEXCON 深圳国际电子展",
    "address": "ELEXCON 深圳国际电子展",
    "startAt": "2026-01-16T02:00:00.000Z",
    "endAt": "2026-01-16T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://elexcon.com/en",
    "sourceId": "elexcon-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-eiotexpo-shenzhen-c011df998b",
    "slug": "e-iot-嵌入式与物联网展-c011df998b",
    "title": "E-IOT 嵌入式与物联网展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "E-IOT 嵌入式与物联网展",
      "展会"
    ],
    "district": "福田",
    "venue": "E-IOT 嵌入式与物联网展",
    "address": "E-IOT 嵌入式与物联网展",
    "startAt": "2026-08-26T02:00:00.000Z",
    "endAt": "2026-08-26T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.eiotexpo.com/",
    "sourceId": "eiotexpo-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "published",
    "weeklyFeatured": true,
    "publicListingTier": "featured",
    "publicScore": 100,
    "childSafetyComplete": true
  },
  {
    "id": "live-luma-shenzhen-0052964fcf",
    "slug": "luma-深圳线索页-0052964fcf",
    "title": "Luma 深圳线索页",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "社科讲座",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "Luma 深圳活动"
    ],
    "district": "福田",
    "venue": "Luma 深圳活动",
    "address": "Luma 深圳活动",
    "startAt": "2026-06-08T10:00:00.000Z",
    "endAt": "2026-06-08T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核",
      "来源建议再复核"
    ],
    "officialUrl": "https://lu.ma/discover?location=Shenzhen",
    "sourceId": "luma-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-hackquest-shenzhen-hackathons-400b6bd7dd",
    "slug": "hackquest-深圳-hackathon-400b6bd7dd",
    "title": "HackQuest 深圳 Hackathon",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "Hackathon",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "HackQuest 深圳 Hackathon"
    ],
    "district": "福田",
    "venue": "HackQuest 深圳 Hackathon",
    "address": "HackQuest 深圳 Hackathon",
    "startAt": "2026-06-09T10:00:00.000Z",
    "endAt": "2026-06-09T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.hackquest.io/en/hackathons/AI-%C3%97-Web3-%E9%BB%91%E5%AE%A2%E6%9D%BE%E6%B7%B1%E5%9C%B3%E7%AB%99",
    "sourceId": "hackquest-shenzhen-hackathons",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-hackathonradar-shenzhen-b9d95095f9",
    "slug": "hackathonradar-深圳线索-b9d95095f9",
    "title": "HackathonRadar 深圳线索",
    "summary": "学习交流类活动，适合按主题和时间筛选。",
    "category": "Hackathon",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "HackathonRadar 深圳线索"
    ],
    "district": "福田",
    "venue": "HackathonRadar 深圳线索",
    "address": "HackathonRadar 深圳线索",
    "startAt": "2026-05-29T10:00:00.000Z",
    "endAt": "2026-05-29T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "学习相关性待复核"
    ],
    "officialUrl": "https://www.hackathonradar.com/database/hackathon/9a9d9772-703e-4263-b163-c1f52cb784a8",
    "sourceId": "hackathonradar-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-sdcon-tech-conference-7afafb3bd1",
    "slug": "sdcon-技术大会-7afafb3bd1",
    "title": "SDCon 技术大会",
    "summary": "技术与产业主题，适合关注趋势和实践机会。",
    "category": "技术大会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "SDCon 技术大会"
    ],
    "district": "福田",
    "venue": "SDCon 技术大会",
    "address": "SDCon 技术大会",
    "startAt": "2026-05-30T10:00:00.000Z",
    "endAt": "2026-05-30T12:00:00.000Z",
    "dateNote": "时间见活动页",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "进阶",
    "recommendation": "适合关注 AI、技术实践或产业变化的人。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "时间待核对",
      "名额和变更看活动页",
      "来源建议再复核"
    ],
    "officialUrl": "https://sdcon.com.cn/",
    "sourceId": "sdcon-tech-conference",
    "lastConfirmedAt": "2026-05-28",
    "status": "uncertain",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  },
  {
    "id": "live-iotexpo-shenzhen-6ede8976aa",
    "slug": "iote-深圳物联网展-6ede8976aa",
    "title": "IOTE 深圳物联网展",
    "summary": "展会体验类活动，适合现场了解新内容。",
    "category": "科技展会",
    "audience": [
      "adult"
    ],
    "tags": [
      "真实采集",
      "IOTE 深圳物联网展",
      "展会"
    ],
    "district": "福田",
    "venue": "IOTE 深圳物联网展",
    "address": "IOTE 深圳物联网展",
    "startAt": "2020-07-31T02:00:00.000Z",
    "endAt": "2020-07-31T04:00:00.000Z",
    "priceType": "公益",
    "priceNote": "见活动页",
    "reservationRequired": true,
    "difficulty": "入门",
    "recommendation": "适合先了解主题，再决定是否报名。",
    "bestFor": "适合成人学习、行业交流或城市文化探索。",
    "cautions": [
      "出发前再看时间",
      "名额和变更看活动页"
    ],
    "officialUrl": "https://www.iotexpo.com.cn/sz/",
    "sourceId": "iotexpo-shenzhen",
    "lastConfirmedAt": "2026-05-28",
    "status": "expired",
    "weeklyFeatured": false,
    "childSafetyComplete": true
  }
] satisfies Activity[];
