import type { Activity, ActivitySource } from "./types";

export const sampleSources: ActivitySource[] = [
  {
    id: "nanshan-tech-museum",
    name: "南山科技馆",
    type: "venue",
    url: "https://example.com/nanshan-tech",
    trustLevel: "high",
    lastChecked: "2026-05-08"
  },
  {
    id: "shenzhen-book-city",
    name: "深圳书城",
    type: "bookstore",
    url: "https://example.com/shenzhen-book-city",
    trustLevel: "high",
    lastChecked: "2026-05-08"
  },
  {
    id: "tech-community",
    name: "深圳技术社区",
    type: "community",
    url: "https://example.com/shenzhen-tech-community",
    trustLevel: "medium",
    lastChecked: "2026-05-08"
  }
];

export const sampleActivities: Activity[] = [
  {
    id: "a1",
    slug: "nanshan-ai-family-day",
    title: "南山 AI 互动体验日",
    summary: "适合第一次带孩子接触 AI 展示和互动装置的周末活动。",
    category: "亲子科技",
    audience: ["family"],
    tags: ["AI", "亲子同行", "互动体验"],
    district: "南山",
    venue: "南山科技馆",
    address: "深圳市南山区科技园片区",
    startAt: "2026-05-16T14:00:00+08:00",
    endAt: "2026-05-16T16:00:00+08:00",
    priceType: "免费",
    priceNote: "免费，需提前预约",
    reservationRequired: true,
    ageBand: "8-12 岁",
    difficulty: "入门",
    recommendation: "有互动环节，不只是看展，适合孩子建立对 AI 的第一印象。",
    bestFor: "想带孩子接触科技展陈的家庭。",
    cautions: ["低龄儿童需要家长全程陪同", "预约名额可能提前满"],
    officialUrl: "https://example.com/events/nanshan-ai-family-day",
    sourceId: "nanshan-tech-museum",
    lastConfirmedAt: "2026-05-08",
    status: "published",
    weeklyFeatured: true,
    childSafetyComplete: true
  },
  {
    id: "a2",
    slug: "ai-product-meetup",
    title: "AI 产品实践 Meetup",
    summary: "面向产品、技术和创业者的 AI 应用交流活动。",
    category: "技术大会",
    audience: ["adult"],
    tags: ["AI", "产品", "创业"],
    district: "福田",
    venue: "深业上城共享会议厅",
    address: "深圳市福田区皇岗路",
    startAt: "2026-05-17T19:30:00+08:00",
    endAt: "2026-05-17T21:30:00+08:00",
    priceType: "收费",
    priceNote: "早鸟票 39 元",
    reservationRequired: true,
    difficulty: "进阶",
    recommendation: "主题聚焦真实产品落地，适合认识深圳 AI 应用圈子。",
    bestFor: "产品经理、开发者、创业者。",
    cautions: ["不适合儿童", "现场座位有限"],
    officialUrl: "https://example.com/events/ai-product-meetup",
    sourceId: "tech-community",
    lastConfirmedAt: "2026-05-08",
    status: "published",
    weeklyFeatured: true,
    childSafetyComplete: true
  },
  {
    id: "a3",
    slug: "social-science-reading-salon",
    title: "城市与技术社科读书沙龙",
    summary: "围绕城市生活、技术变化和公共空间的读书讨论。",
    category: "读书沙龙",
    audience: ["adult"],
    tags: ["社科", "读书", "城市"],
    district: "南山",
    venue: "深圳书城南山城",
    address: "深圳市南山区中心路",
    startAt: "2026-05-18T15:00:00+08:00",
    endAt: "2026-05-18T17:00:00+08:00",
    priceType: "公益",
    priceNote: "公益活动，需报名",
    reservationRequired: true,
    difficulty: "入门",
    recommendation: "门槛不高，但主题能帮助成人从技术之外理解城市变化。",
    bestFor: "喜欢读书、城市议题和公共讨论的成人。",
    cautions: ["建议提前阅读推荐章节"],
    officialUrl: "https://example.com/events/social-science-reading-salon",
    sourceId: "shenzhen-book-city",
    lastConfirmedAt: "2026-05-08",
    status: "published",
    weeklyFeatured: true,
    childSafetyComplete: true
  },
  {
    id: "a4",
    slug: "shenzhen-game-expo-family",
    title: "深圳游戏体验展亲子上午场",
    summary: "面向家庭的游戏互动体验和游戏制作启蒙讲解。",
    category: "游戏展会",
    audience: ["family", "adult"],
    tags: ["游戏", "亲子同行", "创作启蒙"],
    district: "宝安",
    venue: "宝安国际会展中心",
    address: "深圳市宝安区福海街道展城路",
    startAt: "2026-05-19T10:00:00+08:00",
    endAt: "2026-05-19T12:00:00+08:00",
    priceType: "收费",
    priceNote: "家庭票 99 元起",
    reservationRequired: true,
    ageBand: "10 岁以上",
    difficulty: "入门",
    recommendation: "比单纯试玩更有学习价值，包含游戏制作流程讲解。",
    bestFor: "对游戏、动画和互动媒体感兴趣的家庭。",
    cautions: ["展馆较大，建议预留交通时间", "部分区域声音较大"],
    officialUrl: "https://example.com/events/shenzhen-game-expo-family",
    sourceId: "tech-community",
    lastConfirmedAt: "2026-05-08",
    status: "published",
    weeklyFeatured: true,
    childSafetyComplete: true
  },
  {
    id: "a5",
    slug: "hardware-hackathon-weekend",
    title: "周末硬件 Hackathon",
    summary: "围绕智能硬件原型制作的两天协作挑战。",
    category: "Hackathon",
    audience: ["adult"],
    tags: ["硬件", "Hackathon", "创客"],
    district: "南山",
    venue: "深圳湾创业广场",
    address: "深圳市南山区高新南九道",
    startAt: "2026-05-16T09:30:00+08:00",
    endAt: "2026-05-17T18:00:00+08:00",
    priceType: "免费",
    priceNote: "免费，需团队报名",
    reservationRequired: true,
    difficulty: "专业",
    recommendation: "适合有开发或硬件基础的人高密度认识同好。",
    bestFor: "开发者、硬件工程师、创客团队。",
    cautions: ["强度较高", "不适合无基础体验"],
    officialUrl: "https://example.com/events/hardware-hackathon-weekend",
    sourceId: "tech-community",
    lastConfirmedAt: "2026-05-08",
    status: "published",
    weeklyFeatured: true,
    childSafetyComplete: true
  },
  {
    id: "a6",
    slug: "electronics-maker-fair",
    title: "电子创客开放日",
    summary: "电子制作、传感器和开源硬件的展示与体验。",
    category: "电子展会",
    audience: ["family", "adult"],
    tags: ["电子", "创客", "开源硬件"],
    district: "福田",
    venue: "华强北创新中心",
    address: "深圳市福田区华强北路",
    startAt: "2026-05-18T10:30:00+08:00",
    endAt: "2026-05-18T16:30:00+08:00",
    priceType: "免费",
    priceNote: "免费入场，部分工作坊收费",
    reservationRequired: false,
    ageBand: "9 岁以上",
    difficulty: "入门",
    recommendation: "深圳本地特色很强，能把电子产业和动手体验连接起来。",
    bestFor: "想理解深圳电子产业和创客文化的家庭或成人。",
    cautions: ["工作坊名额有限", "低龄儿童需家长陪同"],
    officialUrl: "https://example.com/events/electronics-maker-fair",
    sourceId: "tech-community",
    lastConfirmedAt: "2026-05-08",
    status: "published",
    weeklyFeatured: true,
    childSafetyComplete: true
  },
  {
    id: "a7",
    slug: "cancelled-ai-lecture",
    title: "已取消的 AI 公开课样例",
    summary: "用于验证取消状态不会进入精选。",
    category: "技术大会",
    audience: ["adult"],
    tags: ["AI"],
    district: "南山",
    venue: "测试场地",
    address: "深圳市南山区",
    startAt: "2026-05-15T19:00:00+08:00",
    endAt: "2026-05-15T21:00:00+08:00",
    priceType: "免费",
    priceNote: "免费",
    reservationRequired: true,
    difficulty: "入门",
    recommendation: "取消状态样例。",
    bestFor: "测试用。",
    cautions: ["请勿按原计划前往现场"],
    officialUrl: "https://example.com/events/cancelled-ai-lecture",
    sourceId: "tech-community",
    lastConfirmedAt: "2026-05-08",
    status: "cancelled",
    weeklyFeatured: false,
    childSafetyComplete: true
  },
  {
    id: "a8",
    slug: "child-safety-weak-sample",
    title: "儿童科技体验信息不足样例",
    summary: "用于验证儿童相关信息不足时不能进入亲子精选。",
    category: "亲子科技",
    audience: ["family"],
    tags: ["亲子"],
    district: "龙岗",
    venue: "测试场地",
    address: "深圳市龙岗区",
    startAt: "2026-05-19T14:00:00+08:00",
    endAt: "2026-05-19T15:30:00+08:00",
    priceType: "免费",
    priceNote: "免费",
    reservationRequired: false,
    difficulty: "入门",
    recommendation: "儿童信息不足样例。",
    bestFor: "测试用。",
    cautions: [],
    officialUrl: "https://example.com/events/child-safety-weak-sample",
    sourceId: "tech-community",
    lastConfirmedAt: "2026-05-08",
    status: "published",
    weeklyFeatured: false,
    childSafetyComplete: false
  }
];
